-- Seed materials table with 50 common metallographic materials
-- This seed file populates the materials table with diverse materials used in metallography

INSERT INTO materials (
  name, slug, category, alternative_names, tags,
  hardness, hardness_hb, hardness_hrc, hardness_hv, density, melting_point_celsius,
  tensile_strength_mpa, yield_strength_mpa,
  composition, microstructure,
  material_type, hardness_category, work_hardening, magnetic, corrosion_resistance,
  heat_treatment, annealing_temperature_celsius,
  sectioning_notes, mounting_notes, grinding_notes, polishing_notes, etching_notes,
  recommended_grinding_sequence, recommended_polishing_sequence,
  common_etchants,
  applications, typical_uses, detailed_description,
  status, featured, sort_order
) VALUES

-- Carbon Steels
('AISI 1018 Carbon Steel', 'aisi-1018-carbon-steel', 'Carbon Steel', ARRAY['1018', 'C1018', 'SAE 1018'], ARRAY['low-carbon', 'machinable', 'general-purpose'],
  '126 HB', 126, NULL, NULL, 7.87, 1510, 440, 370,
  'Fe-0.18C-0.75Mn-0.04P-0.05S', 'Ferrite and pearlite',
  'alloy', 'soft', false, true, 'low',
  'Normalized or annealed', 870,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital (2% nitric acid in ethanol) for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['General construction', 'Machinery components'], ARRAY['Shafts', 'Bolts', 'Gears'], 'Low carbon steel with excellent machinability and weldability. Commonly used in general construction and machinery.',
  'published', true, 1),

('AISI 1045 Carbon Steel', 'aisi-1045-carbon-steel', 'Carbon Steel', ARRAY['1045', 'C1045', 'SAE 1045'], ARRAY['medium-carbon', 'heat-treatable', 'high-strength'],
  '170 HB', 170, NULL, NULL, 7.87, 1495, 625, 530,
  'Fe-0.45C-0.75Mn-0.04P-0.05S', 'Ferrite and pearlite (annealed), martensite (quenched)',
  'alloy', 'medium', false, true, 'low',
  'Normalized, quenched and tempered', 850,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital (2% nitric acid in ethanol) for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Shafts', 'Gears', 'Axles'], ARRAY['Automotive components', 'Machine parts'], 'Medium carbon steel with good strength and hardness. Can be heat treated for improved mechanical properties.',
  'published', true, 2),

('AISI 1095 High Carbon Steel', 'aisi-1095-high-carbon-steel', 'Carbon Steel', ARRAY['1095', 'C1095', 'SAE 1095'], ARRAY['high-carbon', 'tool-steel', 'spring-steel'],
  '190 HB', 190, NULL, NULL, 7.87, 1480, 665, 570,
  'Fe-0.95C-0.40Mn-0.04P-0.05S', 'Pearlite and cementite (annealed), martensite (quenched)',
  'alloy', 'hard', false, true, 'low',
  'Normalized, quenched and tempered', 790,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital (2% nitric acid in ethanol) for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Knives', 'Springs', 'Cutting tools'], ARRAY['Blades', 'Saws', 'Chisels'], 'High carbon steel with excellent hardness and wear resistance. Used for cutting tools and springs.',
  'published', false, 3),

-- Stainless Steels
('304 Stainless Steel', '304-stainless-steel', 'Stainless Steel', ARRAY['304', 'AISI 304', '18-8', 'EN 1.4301'], ARRAY['austenitic', 'corrosion-resistant', 'food-grade'],
  '123 HB', 123, NULL, NULL, 8.0, 1400, 515, 205,
  'Fe-18Cr-8Ni-0.08C', 'Austenite with some delta ferrite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed at 1050-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia (10ml glycerol, 15ml HCl, 5ml HNO3) for 10-30 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Aqua Regia', 'Electrolytic 10% Oxalic'],
  ARRAY['Food processing', 'Chemical equipment', 'Architecture'], ARRAY['Kitchen equipment', 'Tanks', 'Pipes'], 'Most common austenitic stainless steel with excellent corrosion resistance and formability.',
  'published', true, 10),

('316 Stainless Steel', '316-stainless-steel', 'Stainless Steel', ARRAY['316', 'AISI 316', '18-10', 'EN 1.4401'], ARRAY['austenitic', 'corrosion-resistant', 'marine'],
  '149 HB', 149, NULL, NULL, 8.0, 1375, 515, 205,
  'Fe-16Cr-10Ni-2Mo-0.08C', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed at 1050-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia (10ml glycerol, 15ml HCl, 5ml HNO3) for 10-30 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Aqua Regia', 'Electrolytic 10% Oxalic'],
  ARRAY['Marine applications', 'Chemical processing', 'Pharmaceutical'], ARRAY['Boat fittings', 'Heat exchangers', 'Medical devices'], 'Molybdenum-bearing austenitic stainless steel with superior corrosion resistance, especially to chlorides.',
  'published', true, 11),

('410 Stainless Steel', '410-stainless-steel', 'Stainless Steel', ARRAY['410', 'AISI 410', 'EN 1.4006'], ARRAY['martensitic', 'hardenable', 'magnetic'],
  '217 HB', 217, NULL, NULL, 7.7, 1480, 480, 275,
  'Fe-12Cr-0.15C', 'Martensite (quenched), tempered martensite',
  'alloy', 'hard', false, true, 'medium',
  'Quenched and tempered', 950,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Vilella''s reagent (1g picric acid, 5ml HCl, 100ml ethanol) for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Vilella''s Reagent', '2% Nital'],
  ARRAY['Cutlery', 'Valves', 'Pumps'], ARRAY['Knives', 'Surgical instruments', 'Fasteners'], 'Martensitic stainless steel that can be hardened by heat treatment. Magnetic and less corrosion resistant than austenitic grades.',
  'published', false, 12),

('17-4 PH Stainless Steel', '17-4-ph-stainless-steel', 'Stainless Steel', ARRAY['17-4 PH', '630', 'AISI 630', 'EN 1.4542'], ARRAY['precipitation-hardening', 'high-strength', 'aerospace'],
  '363 HB', 363, 40, NULL, 7.8, 1400, 1310, 1170,
  'Fe-16Cr-4Ni-4Cu-0.07C', 'Martensite with Cu-rich precipitates',
  'alloy', 'very-hard', false, true, 'high',
  'Solution treated and aged', 1040,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Aerospace', 'Nuclear', 'Chemical processing'], ARRAY['Turbine blades', 'Shafts', 'Valves'], 'Precipitation-hardening stainless steel with excellent strength and corrosion resistance. Used in demanding applications.',
  'published', true, 13),

-- Aluminum Alloys
('6061 Aluminum', '6061-aluminum', 'Aluminum Alloy', ARRAY['6061', 'AA6061', 'AlMg1SiCu'], ARRAY['heat-treatable', 'weldable', 'general-purpose'],
  '95 HB', 95, NULL, NULL, 2.70, 582, 310, 276,
  'Al-1.0Mg-0.6Si-0.25Cu-0.2Cr', 'Alpha aluminum with Mg2Si precipitates',
  'alloy', 'soft', true, false, 'medium',
  'Solution treated and aged (T6 temper)', 530,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent (2ml HF, 3ml HCl, 5ml HNO3, 190ml H2O) for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Marine', 'Automotive'], ARRAY['Aircraft structures', 'Boat hulls', 'Bicycle frames'], 'Most versatile heat-treatable aluminum alloy with good strength, weldability, and corrosion resistance.',
  'published', true, 20),

('7075 Aluminum', '7075-aluminum', 'Aluminum Alloy', ARRAY['7075', 'AA7075', 'AlZn5.5MgCu'], ARRAY['high-strength', 'aerospace', 'heat-treatable'],
  '150 HB', 150, NULL, NULL, 2.81, 477, 572, 503,
  'Al-5.6Zn-2.5Mg-1.6Cu-0.23Cr', 'Alpha aluminum with Zn-Mg-Cu precipitates',
  'alloy', 'medium', true, false, 'medium',
  'Solution treated and aged (T6 temper)', 470,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent (2ml HF, 3ml HCl, 5ml HNO3, 190ml H2O) for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Military', 'Sports equipment'], ARRAY['Aircraft structures', 'Bicycle frames', 'Golf clubs'], 'High-strength aluminum alloy with excellent fatigue resistance. Used in aerospace and high-performance applications.',
  'published', true, 21),

('2024 Aluminum', '2024-aluminum', 'Aluminum Alloy', ARRAY['2024', 'AA2024', 'AlCu4Mg1'], ARRAY['high-strength', 'aerospace', 'heat-treatable'],
  '120 HB', 120, NULL, NULL, 2.78, 502, 469, 324,
  'Al-4.4Cu-1.5Mg-0.6Mn', 'Alpha aluminum with Cu-Mg precipitates',
  'alloy', 'soft', true, false, 'low',
  'Solution treated and aged (T6 temper)', 495,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent (2ml HF, 3ml HCl, 5ml HNO3, 190ml H2O) for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Military'], ARRAY['Aircraft structures', 'Rivets', 'Wing skins'], 'High-strength aluminum-copper alloy widely used in aircraft structures. Excellent fatigue resistance.',
  'published', false, 22),

('3003 Aluminum', '3003-aluminum', 'Aluminum Alloy', ARRAY['3003', 'AA3003', 'AlMn1Cu'], ARRAY['non-heat-treatable', 'weldable', 'general-purpose'],
  '28 HB', 28, NULL, NULL, 2.73, 643, 110, 41,
  'Al-1.2Mn-0.12Cu', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'medium',
  'Annealed or strain hardened', 415,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent (2ml HF, 3ml HCl, 5ml HNO3, 190ml H2O) for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Food processing', 'Chemical equipment', 'General fabrication'], ARRAY['Cooking utensils', 'Tanks', 'Sheet metal'], 'Non-heat-treatable aluminum alloy with good formability and corrosion resistance. Commonly used in sheet metal applications.',
  'published', false, 23),

-- Copper Alloys
('C11000 Electrolytic Tough Pitch Copper', 'c11000-electrolytic-tough-pitch-copper', 'Copper Alloy', ARRAY['C11000', 'ETP Copper', 'Cu-ETP'], ARRAY['electrical', 'thermal', 'pure-copper'],
  '42 HB', 42, NULL, NULL, 8.94, 1083, 220, 69,
  'Cu-99.9Cu-0.04O', 'Alpha copper with Cu2O particles',
  'metal', 'soft', true, false, 'high',
  'Annealed', 400,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate (10g in 100ml H2O) or ferric chloride solution',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Electrical', 'Electronics', 'Heat exchangers'], ARRAY['Wire', 'Busbars', 'Heat exchangers'], 'Pure copper with excellent electrical and thermal conductivity. Most common copper grade for electrical applications.',
  'published', true, 30),

('C26000 Cartridge Brass', 'c26000-cartridge-brass', 'Copper Alloy', ARRAY['C26000', '70/30 Brass', 'Cartridge Brass'], ARRAY['brass', 'machinable', 'general-purpose'],
  '100 HB', 100, NULL, NULL, 8.53, 915, 380, 125,
  'Cu-30Zn', 'Alpha brass (single phase)',
  'alloy', 'soft', true, false, 'medium',
  'Annealed', 425,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate (10g in 100ml H2O) or ferric chloride solution',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Ammunition', 'Hardware', 'Decorative'], ARRAY['Cartridge cases', 'Fasteners', 'Architectural'], 'Most common brass alloy with excellent formability and machinability. Named for its use in cartridge cases.',
  'published', true, 31),

('C36000 Free-Cutting Brass', 'c36000-free-cutting-brass', 'Copper Alloy', ARRAY['C36000', '360 Brass', 'Free-Cutting Brass'], ARRAY['brass', 'machinable', 'lead-bearing'],
  '80 HB', 80, NULL, NULL, 8.50, 900, 310, 125,
  'Cu-35.5Zn-3Pb', 'Alpha brass with lead particles',
  'alloy', 'soft', true, false, 'medium',
  'As fabricated', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate (10g in 100ml H2O) or ferric chloride solution',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Machining', 'Hardware', 'Plumbing'], ARRAY['Screws', 'Nuts', 'Fittings'], 'Lead-bearing brass with excellent machinability. Used for high-volume machined parts.',
  'published', false, 32),

('C71500 Cupronickel 70-30', 'c71500-cupronickel-70-30', 'Copper Alloy', ARRAY['C71500', '70-30 Cupronickel', 'CuNi30'], ARRAY['corrosion-resistant', 'marine', 'nickel-alloy'],
  '65 HB', 65, NULL, NULL, 8.94, 1170, 380, 125,
  'Cu-30Ni-0.7Fe-0.5Mn', 'Alpha copper-nickel solid solution',
  'alloy', 'soft', true, false, 'excellent',
  'Annealed', 600,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate (10g in 100ml H2O) or ferric chloride solution',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Marine', 'Desalination', 'Heat exchangers'], ARRAY['Condenser tubes', 'Heat exchangers', 'Marine hardware'], 'Copper-nickel alloy with excellent corrosion resistance, especially in seawater. Used extensively in marine applications.',
  'published', false, 33),

-- Titanium Alloys
('Ti-6Al-4V (Grade 5)', 'ti-6al-4v-grade-5', 'Titanium Alloy', ARRAY['Ti-6Al-4V', 'Grade 5', 'Ti64', 'ASTM B348'], ARRAY['aerospace', 'biomedical', 'high-strength'],
  '349 HB', 349, 36, NULL, 4.43, 1604, 930, 880,
  'Ti-6Al-4V', 'Alpha-beta titanium with alpha and transformed beta',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 955,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent (2ml HF, 4ml HNO3, 94ml H2O) for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Aerospace', 'Biomedical', 'Marine'], ARRAY['Aircraft components', 'Medical implants', 'Marine hardware'], 'Most common titanium alloy with excellent strength-to-weight ratio and corrosion resistance. Used in aerospace and biomedical applications.',
  'published', true, 40),

('Commercially Pure Titanium (Grade 2)', 'commercially-pure-titanium-grade-2', 'Titanium Alloy', ARRAY['CP Ti', 'Grade 2', 'ASTM B265'], ARRAY['corrosion-resistant', 'biomedical', 'pure-titanium'],
  '120 HB', 120, NULL, NULL, 4.51, 1668, 345, 275,
  'Ti-0.25O-0.3Fe', 'Alpha titanium',
  'metal', 'soft', true, false, 'excellent',
  'Annealed', 700,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent (2ml HF, 4ml HNO3, 94ml H2O) for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Chemical processing', 'Biomedical', 'Marine'], ARRAY['Chemical equipment', 'Medical implants', 'Heat exchangers'], 'Unalloyed titanium with excellent corrosion resistance and biocompatibility. Used in chemical processing and medical applications.',
  'published', true, 41),

('Ti-6Al-2Sn-4Zr-2Mo (Grade 5)', 'ti-6al-2sn-4zr-2mo', 'Titanium Alloy', ARRAY['Ti-6-2-4-2', 'Ti6242'], ARRAY['aerospace', 'high-temperature', 'beta-rich'],
  '365 HB', 365, 38, NULL, 4.54, 1600, 1035, 970,
  'Ti-6Al-2Sn-4Zr-2Mo', 'Alpha-beta titanium',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 955,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent (2ml HF, 4ml HNO3, 94ml H2O) for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Aerospace', 'Gas turbines'], ARRAY['Jet engine components', 'Compressor blades'], 'High-strength titanium alloy used in elevated temperature applications. Common in jet engine components.',
  'published', false, 42),

-- Nickel Alloys
('Inconel 625', 'inconel-625', 'Nickel Alloy', ARRAY['IN625', 'UNS N06625', 'Alloy 625'], ARRAY['corrosion-resistant', 'high-temperature', 'nickel-base'],
  '150 HB', 150, NULL, NULL, 8.44, 1290, 760, 345,
  'Ni-21.5Cr-9Mo-3.6Nb-0.2Ti', 'Austenite with gamma prime and carbides',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Aerospace', 'Chemical processing', 'Marine'], ARRAY['Gas turbines', 'Heat exchangers', 'Chemical reactors'], 'Nickel-chromium-molybdenum superalloy with excellent corrosion resistance and high-temperature strength.',
  'published', true, 50),

('Monel 400', 'monel-400', 'Nickel Alloy', ARRAY['Monel 400', 'UNS N04400', 'Alloy 400'], ARRAY['corrosion-resistant', 'marine', 'nickel-copper'],
  '120 HB', 120, NULL, NULL, 8.80, 1300, 550, 240,
  'Ni-31.5Cu-0.2Fe-0.2Mn', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Annealed', 900,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or ferric chloride solution',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Ferric Chloride'],
  ARRAY['Marine', 'Chemical processing', 'Oil and gas'], ARRAY['Marine hardware', 'Valves', 'Pumps'], 'Nickel-copper alloy with excellent corrosion resistance in seawater and many chemical environments.',
  'published', false, 51),

('Hastelloy C-276', 'hastelloy-c-276', 'Nickel Alloy', ARRAY['Hastelloy C-276', 'UNS N10276', 'Alloy C-276'], ARRAY['corrosion-resistant', 'chemical', 'nickel-base'],
  '210 HB', 210, NULL, NULL, 8.89, 1325, 690, 315,
  'Ni-16Cr-16Mo-4W-0.01C', 'Austenite',
  'alloy', 'medium', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Pollution control', 'Pharmaceutical'], ARRAY['Chemical reactors', 'Scrubbers', 'Heat exchangers'], 'Nickel-molybdenum-chromium superalloy with outstanding corrosion resistance to a wide range of chemicals.',
  'published', false, 52),

-- Tool Steels
('D2 Tool Steel', 'd2-tool-steel', 'Tool Steel', ARRAY['D2', 'AISI D2', '1.2379'], ARRAY['cold-work', 'high-carbon', 'high-chromium'],
  '255 HB', 255, NULL, NULL, 7.70, 1420, 760, 620,
  'Fe-1.5C-12Cr-0.8Mo-0.9V', 'Martensite with primary and secondary carbides',
  'alloy', 'very-hard', false, true, 'medium',
  'Quenched and tempered', 1025,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Cutting tools', 'Dies', 'Molds'], ARRAY['Blades', 'Punches', 'Forming dies'], 'High-carbon, high-chromium tool steel with excellent wear resistance. Used for cold-work applications.',
  'published', false, 60),

('M2 High-Speed Steel', 'm2-high-speed-steel', 'Tool Steel', ARRAY['M2', 'AISI M2', '1.3343'], ARRAY['high-speed-steel', 'cutting-tools', 'tungsten'],
  '262 HB', 262, NULL, NULL, 8.10, 1420, 760, 620,
  'Fe-0.85C-6W-5Mo-4Cr-2V', 'Martensite with complex carbides',
  'alloy', 'very-hard', false, true, 'low',
  'Quenched and tempered', 1220,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Cutting tools', 'Drills', 'End mills'], ARRAY['Drill bits', 'Milling cutters', 'Taps'], 'Tungsten-molybdenum high-speed steel with excellent hot hardness. Used for cutting tools.',
  'published', false, 61),

-- Cast Irons
('Gray Cast Iron', 'gray-cast-iron', 'Cast Iron', ARRAY['Gray Iron', 'Flake Graphite Iron'], ARRAY['cast-iron', 'graphite', 'machinable'],
  '187 HB', 187, NULL, NULL, 7.1, 1150, 250, NULL,
  'Fe-3.5C-2.5Si-0.5Mn', 'Pearlite matrix with flake graphite',
  'alloy', 'medium', false, true, 'low',
  'As cast or annealed', 900,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Machinery', 'Construction'], ARRAY['Engine blocks', 'Machine bases', 'Pipes'], 'Cast iron with flake graphite providing good machinability and damping capacity. Most common cast iron type.',
  'published', true, 70),

('Ductile Cast Iron', 'ductile-cast-iron', 'Cast Iron', ARRAY['Nodular Iron', 'Spheroidal Graphite Iron', 'SG Iron'], ARRAY['cast-iron', 'graphite', 'ductile'],
  '217 HB', 217, NULL, NULL, 7.1, 1150, 414, 276,
  'Fe-3.5C-2.5Si-0.5Mn-0.04Mg', 'Pearlite matrix with spheroidal graphite',
  'alloy', 'medium', false, true, 'low',
  'As cast or normalized', 900,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Pipes', 'Valves'], ARRAY['Crankshafts', 'Gears', 'Pipe fittings'], 'Cast iron with spheroidal graphite providing improved ductility and strength compared to gray iron.',
  'published', true, 71),

('White Cast Iron', 'white-cast-iron', 'Cast Iron', ARRAY['White Iron', 'Chilled Iron'], ARRAY['cast-iron', 'hard', 'abrasion-resistant'],
  '450 HB', 450, NULL, NULL, 7.7, 1150, 275, NULL,
  'Fe-3.5C-0.5Si-0.5Mn', 'Cementite and pearlite (no graphite)',
  'alloy', 'very-hard', false, true, 'low',
  'As cast', NULL,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Mining', 'Abrasion-resistant applications'], ARRAY['Mill liners', 'Grinding balls', 'Pump parts'], 'Hard, brittle cast iron with cementite instead of graphite. Excellent abrasion resistance but poor machinability.',
  'published', false, 72),

-- Magnesium Alloys
('AZ31B Magnesium', 'az31b-magnesium', 'Magnesium Alloy', ARRAY['AZ31B', 'Mg-3Al-1Zn'], ARRAY['lightweight', 'aerospace', 'weldable'],
  '49 HB', 49, NULL, NULL, 1.77, 605, 290, 200,
  'Mg-3Al-1Zn-0.2Mn', 'Alpha magnesium with Al-Mn particles',
  'alloy', 'soft', true, false, 'low',
  'As fabricated or annealed', 345,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Acetic picral (10ml acetic acid, 4.2g picric acid, 10ml H2O, 70ml ethanol)',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Acetic Picral', 'Glycol Etchant'],
  ARRAY['Aerospace', 'Automotive', 'Electronics'], ARRAY['Aircraft components', 'Laptop cases', 'Automotive parts'], 'Lightweight magnesium alloy with good formability and weldability. Used in weight-critical applications.',
  'published', false, 80),

-- Zinc Alloys
('Zamak 3', 'zamak-3', 'Zinc Alloy', ARRAY['Zamak 3', 'ZA3', 'ASTM AG40A'], ARRAY['die-cast', 'zinc', 'general-purpose'],
  '82 HB', 82, NULL, NULL, 6.6, 387, 283, 228,
  'Zn-4Al-0.04Mg', 'Alpha zinc with Al-rich phase',
  'alloy', 'soft', false, false, 'low',
  'As cast', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '1% nital or chromic acid solution',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['1% Nital', 'Chromic Acid'],
  ARRAY['Die casting', 'Automotive', 'Hardware'], ARRAY['Automotive parts', 'Hardware', 'Toys'], 'Most common zinc die-casting alloy with good castability and mechanical properties.',
  'published', false, 81),

-- Additional Steels
('AISI 4140 Chromium-Molybdenum Steel', 'aisi-4140-chromium-molybdenum-steel', 'Alloy Steel', ARRAY['4140', 'AISI 4140', '42CrMo4'], ARRAY['heat-treatable', 'high-strength', 'machinable'],
  '197 HB', 197, NULL, NULL, 7.85, 1416, 655, 415,
  'Fe-0.40C-1Cr-0.25Mo-0.85Mn', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 845,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Aerospace', 'Automotive', 'Oil and gas'], ARRAY['Shafts', 'Gears', 'Bolts'], 'Chromium-molybdenum steel with excellent hardenability and strength. Used in high-stress applications.',
  'published', true, 4),

('AISI 4340 Nickel-Chromium-Molybdenum Steel', 'aisi-4340-nickel-chromium-molybdenum-steel', 'Alloy Steel', ARRAY['4340', 'AISI 4340', '40NiCrMo4'], ARRAY['high-strength', 'toughness', 'aerospace'],
  '217 HB', 217, NULL, NULL, 7.85, 1427, 745, 470,
  'Fe-0.40C-1.8Ni-0.8Cr-0.25Mo', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 845,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Aerospace', 'Automotive', 'Defense'], ARRAY['Landing gear', 'Crankshafts', 'Bolts'], 'High-strength steel with excellent toughness. Used in critical aerospace and automotive components.',
  'published', true, 5),

('A36 Structural Steel', 'a36-structural-steel', 'Carbon Steel', ARRAY['A36', 'ASTM A36'], ARRAY['structural', 'construction', 'weldable'],
  '119 HB', 119, NULL, NULL, 7.85, 1510, 400, 250,
  'Fe-0.25C-1.03Mn-0.04P-0.05S', 'Ferrite and pearlite',
  'alloy', 'soft', false, true, 'low',
  'As rolled', NULL,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Construction', 'Bridges', 'Buildings'], ARRAY['Beams', 'Plates', 'Structural members'], 'Most common structural steel in the United States. Used in construction and general fabrication.',
  'published', false, 6),

-- Additional Stainless Steels
('2205 Duplex Stainless Steel', '2205-duplex-stainless-steel', 'Stainless Steel', ARRAY['2205', 'UNS S31803', 'Duplex 2205'], ARRAY['duplex', 'corrosion-resistant', 'high-strength'],
  '293 HB', 293, 30, NULL, 7.8, 1420, 620, 450,
  'Fe-22Cr-5Ni-3Mo-0.03C-0.15N', 'Austenite and ferrite (approximately 50/50)',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution annealed at 1020-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Beraha''s reagent or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Beraha''s Reagent', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Oil and gas', 'Marine'], ARRAY['Heat exchangers', 'Pressure vessels', 'Pipes'], 'Duplex stainless steel with high strength and excellent corrosion resistance. Used in demanding applications.',
  'published', true, 14),

('430 Stainless Steel', '430-stainless-steel', 'Stainless Steel', ARRAY['430', 'AISI 430', 'EN 1.4016'], ARRAY['ferritic', 'magnetic', 'decorative'],
  '183 HB', 183, NULL, NULL, 7.7, 1425, 450, 275,
  'Fe-16Cr-0.12C', 'Ferrite',
  'alloy', 'medium', false, true, 'medium',
  'Annealed', 815,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Vilella''s reagent or 2% nital',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Vilella''s Reagent', '2% Nital'],
  ARRAY['Decorative', 'Automotive', 'Kitchen equipment'], ARRAY['Trim', 'Exhaust systems', 'Appliances'], 'Ferritic stainless steel with good corrosion resistance and magnetic properties. Used in decorative and automotive applications.',
  'published', false, 15),

('321 Stainless Steel', '321-stainless-steel', 'Stainless Steel', ARRAY['321', 'AISI 321', 'EN 1.4541'], ARRAY['austenitic', 'stabilized', 'high-temperature'],
  '123 HB', 123, NULL, NULL, 8.0, 1400, 515, 205,
  'Fe-18Cr-10Ni-0.08C-0.4Ti', 'Austenite with TiC particles',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed at 1050-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia for 10-30 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Aqua Regia'],
  ARRAY['High-temperature applications', 'Welded structures'], ARRAY['Exhaust systems', 'Heat exchangers', 'Pressure vessels'], 'Titanium-stabilized austenitic stainless steel for high-temperature applications and welded structures.',
  'published', false, 16),

-- Additional Aluminum Alloys
('5052 Aluminum', '5052-aluminum', 'Aluminum Alloy', ARRAY['5052', 'AA5052', 'AlMg2.5'], ARRAY['non-heat-treatable', 'corrosion-resistant', 'marine'],
  '47 HB', 47, NULL, NULL, 2.68, 607, 228, 193,
  'Al-2.5Mg-0.25Cr', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'high',
  'As fabricated or strain hardened', 345,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Marine', 'Architecture', 'General fabrication'], ARRAY['Marine hardware', 'Sheet metal', 'Tanks'], 'Non-heat-treatable aluminum-magnesium alloy with excellent corrosion resistance, especially in marine environments.',
  'published', false, 24),

('5083 Aluminum', '5083-aluminum', 'Aluminum Alloy', ARRAY['5083', 'AA5083', 'AlMg4.5Mn'], ARRAY['non-heat-treatable', 'marine', 'weldable'],
  '75 HB', 75, NULL, NULL, 2.66, 574, 317, 228,
  'Al-4.5Mg-0.7Mn-0.15Cr', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'excellent',
  'As fabricated', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Marine', 'Cryogenic', 'Pressure vessels'], ARRAY['Ship hulls', 'Cryogenic tanks', 'Pressure vessels'], 'High-strength aluminum-magnesium alloy with excellent corrosion resistance and weldability. Used in marine and cryogenic applications.',
  'published', false, 25),

('2024-T3 Aluminum', '2024-t3-aluminum', 'Aluminum Alloy', ARRAY['2024-T3', 'AA2024-T3'], ARRAY['high-strength', 'aerospace', 'sheet'],
  '120 HB', 120, NULL, NULL, 2.78, 502, 469, 324,
  'Al-4.4Cu-1.5Mg-0.6Mn', 'Alpha aluminum with Cu-Mg precipitates',
  'alloy', 'soft', true, false, 'low',
  'Solution treated and naturally aged', 495,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Military'], ARRAY['Aircraft skins', 'Wing structures'], 'High-strength aluminum-copper alloy in T3 temper. Used extensively in aircraft structures.',
  'published', false, 26),

-- Additional Copper Alloys
('C17200 Beryllium Copper', 'c17200-beryllium-copper', 'Copper Alloy', ARRAY['C17200', 'BeCu', 'Beryllium Copper'], ARRAY['high-strength', 'spring', 'beryllium'],
  '380 HB', 380, 38, NULL, 8.25, 866, 1310, 1170,
  'Cu-1.9Be-0.2Co', 'Alpha copper with beryllium precipitates',
  'alloy', 'very-hard', false, false, 'high',
  'Solution treated and aged', 315,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Electronics', 'Springs', 'Aerospace'], ARRAY['Springs', 'Electrical contacts', 'Aerospace components'], 'High-strength copper-beryllium alloy with excellent spring properties and electrical conductivity.',
  'published', true, 34),

('C95400 Aluminum Bronze', 'c95400-aluminum-bronze', 'Copper Alloy', ARRAY['C95400', 'Aluminum Bronze', '9Al-4Fe-4Ni'], ARRAY['bronze', 'wear-resistant', 'corrosion-resistant'],
  '170 HB', 170, NULL, NULL, 7.45, 1040, 655, 276,
  'Cu-9Al-4Fe-4Ni', 'Alpha copper with beta phase and iron particles',
  'alloy', 'medium', false, false, 'high',
  'As cast or heat treated', 900,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Marine', 'Bearings', 'Gears'], ARRAY['Propellers', 'Bearings', 'Gears'], 'Aluminum bronze with excellent wear resistance and corrosion resistance. Used in marine and bearing applications.',
  'published', false, 35),

('C93200 Leaded Tin Bronze', 'c93200-leaded-tin-bronze', 'Copper Alloy', ARRAY['C93200', 'SAE 660', 'Leaded Bronze'], ARRAY['bronze', 'bearing', 'machinable'],
  '65 HB', 65, NULL, NULL, 8.93, 899, 240, 124,
  'Cu-7Sn-7Pb-0.1P', 'Alpha copper with lead particles',
  'alloy', 'soft', false, false, 'medium',
  'As cast', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Bearings', 'Bushings', 'Gears'], ARRAY['Bushings', 'Bearings', 'Gears'], 'Leaded tin bronze with excellent bearing properties and machinability. Used in bearing and bushing applications.',
  'published', false, 36),

-- Additional Titanium Alloys
('Ti-3Al-2.5V', 'ti-3al-25v', 'Titanium Alloy', ARRAY['Ti-3-2.5', 'Grade 9'], ARRAY['titanium', 'aerospace', 'tubing'],
  '140 HB', 140, NULL, NULL, 4.48, 1600, 620, 483,
  'Ti-3Al-2.5V', 'Alpha-beta titanium',
  'alloy', 'soft', true, false, 'excellent',
  'Annealed', 700,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Aerospace', 'Medical', 'Marine'], ARRAY['Hydraulic tubing', 'Medical devices', 'Marine hardware'], 'Alpha-beta titanium alloy with good strength and formability. Used in tubing and medical applications.',
  'published', false, 43),

('Beta C Titanium', 'beta-c-titanium', 'Titanium Alloy', ARRAY['Beta C', 'Ti-3Al-8V-6Cr-4Mo-4Zr'], ARRAY['beta-titanium', 'high-strength', 'aerospace'],
  '365 HB', 365, 38, NULL, 4.65, 1600, 1170, 1100,
  'Ti-3Al-8V-6Cr-4Mo-4Zr', 'Beta titanium',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 815,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Aerospace', 'Medical'], ARRAY['Aircraft components', 'Medical implants'], 'Beta titanium alloy with very high strength. Used in demanding aerospace and medical applications.',
  'published', false, 44),

-- Additional Nickel Alloys
('Inconel 718', 'inconel-718', 'Nickel Alloy', ARRAY['IN718', 'UNS N07718', 'Alloy 718'], ARRAY['superalloy', 'aerospace', 'precipitation-hardening'],
  '352 HB', 352, 40, NULL, 8.19, 1260, 1276, 1035,
  'Ni-19Cr-18Fe-5Nb-3Mo-0.9Ti-0.5Al', 'Gamma matrix with gamma prime and gamma double prime',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 980,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Aerospace', 'Gas turbines', 'Nuclear'], ARRAY['Jet engines', 'Gas turbines', 'Nuclear reactors'], 'Nickel-based superalloy with excellent high-temperature strength and corrosion resistance. Most widely used superalloy.',
  'published', true, 53),

('Hastelloy X', 'hastelloy-x', 'Nickel Alloy', ARRAY['Hastelloy X', 'UNS N06002', 'Alloy X'], ARRAY['superalloy', 'high-temperature', 'nickel-base'],
  '150 HB', 150, NULL, NULL, 8.22, 1350, 655, 240,
  'Ni-22Cr-18.5Fe-9Mo-0.6W-0.1C', 'Austenite with carbides',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1175,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Aerospace', 'Gas turbines', 'Heat treatment'], ARRAY['Gas turbines', 'Furnace components', 'Heat exchangers'], 'Nickel-based superalloy with excellent high-temperature strength and oxidation resistance.',
  'published', false, 54),

-- Additional Materials
('Waspaloy', 'waspaloy', 'Nickel Alloy', ARRAY['Waspaloy', 'UNS N07001'], ARRAY['superalloy', 'aerospace', 'gas-turbine'],
  '363 HB', 363, 40, NULL, 8.22, 1330, 1140, 795,
  'Ni-19.5Cr-13.5Co-4.3Mo-3Ti-1.4Al', 'Gamma matrix with gamma prime',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 1080,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Aerospace', 'Gas turbines'], ARRAY['Turbine disks', 'Compressor blades'], 'Nickel-based superalloy used in gas turbine engines. Excellent high-temperature strength and creep resistance.',
  'published', false, 55),

('Cobalt-Chromium Alloy (Stellite 6)', 'cobalt-chromium-alloy-stellite-6', 'Cobalt Alloy', ARRAY['Stellite 6', 'CoCr Alloy'], ARRAY['wear-resistant', 'hardfacing', 'cobalt-base'],
  '450 HB', 450, NULL, NULL, 8.44, 1295, 690, 450,
  'Co-30Cr-4.5W-1.2C', 'Cobalt-chromium matrix with carbides',
  'alloy', 'very-hard', false, false, 'high',
  'As cast', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Hardfacing', 'Wear parts', 'Valves'], ARRAY['Valve seats', 'Wear plates', 'Cutting tools'], 'Cobalt-chromium alloy with excellent wear resistance and hardness. Used for hardfacing and wear-resistant applications.',
  'published', false, 90),

('Tantalum', 'tantalum', 'Refractory Metal', ARRAY['Ta', 'Pure Tantalum'], ARRAY['refractory', 'corrosion-resistant', 'high-melting'],
  '45 HB', 45, NULL, NULL, 16.6, 2996, 345, 165,
  'Ta-99.9Ta', 'Body-centered cubic tantalum',
  'metal', 'soft', true, false, 'excellent',
  'Annealed', 1200,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Hydrofluoric acid solution or electrolytic etching',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['HF Solution', 'Electrolytic'],
  ARRAY['Electronics', 'Chemical processing', 'Medical'], ARRAY['Capacitors', 'Chemical equipment', 'Medical implants'], 'Refractory metal with excellent corrosion resistance and biocompatibility. Used in electronics and chemical processing.',
  'published', false, 91),

('Niobium', 'niobium', 'Refractory Metal', ARRAY['Nb', 'Columbium', 'Pure Niobium'], ARRAY['refractory', 'superconducting', 'high-melting'],
  '75 HB', 75, NULL, NULL, 8.57, 2477, 275, 105,
  'Nb-99.9Nb', 'Body-centered cubic niobium',
  'metal', 'soft', true, false, 'high',
  'Annealed', 1000,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Hydrofluoric acid solution or electrolytic etching',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['HF Solution', 'Electrolytic'],
  ARRAY['Superconducting', 'Aerospace', 'Nuclear'], ARRAY['Superconducting magnets', 'Aerospace components', 'Nuclear applications'], 'Refractory metal used in superconducting applications and high-temperature environments.',
  'published', false, 92),

('Molybdenum', 'molybdenum', 'Refractory Metal', ARRAY['Mo', 'Pure Molybdenum'], ARRAY['refractory', 'high-temperature', 'high-melting'],
  '150 HB', 150, NULL, NULL, 10.2, 2623, 345, 240,
  'Mo-99.9Mo', 'Body-centered cubic molybdenum',
  'metal', 'soft', false, false, 'medium',
  'Annealed', 1200,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Hydrofluoric acid solution or electrolytic etching',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['HF Solution', 'Electrolytic'],
  ARRAY['High-temperature', 'Electronics', 'Aerospace'], ARRAY['Furnace components', 'Electronics', 'Aerospace parts'], 'Refractory metal with very high melting point. Used in high-temperature applications and electronics.',
  'published', false, 93);

-- Update slugs using the generate_material_slug function
UPDATE materials SET slug = generate_material_slug(name) WHERE slug IS NULL;

