-- Seed additional materials table with Tungsten and 20 more commonly used manufacturing materials
-- This migration adds materials that are frequently used in manufacturing but weren't in the initial seed

INSERT INTO materials (
  name, slug, category, alternative_names, tags,
  hardness, hardness_hb, hardness_hrc, hardness_hv, density, melting_point_celsius,
  tensile_strength_mpa, yield_strength_mpa,
  composition, microstructure,
  material_type, hardness_category, work_hardening, magnetic, corrosion_resistance,
  heat_treatment, annealing_temperature_celsius,
  sectioning_notes, mounting_notes, grinding_notes, polishing_notes, etching_notes,
  recommended_grinding_sequence, recommended_polishing_sequence,
  common_etchants,
  applications, typical_uses, detailed_description,
  status, featured, sort_order
) VALUES

-- Refractory Metal
('Tungsten', 'tungsten', 'Refractory Metal', ARRAY['W', 'Wolfram', 'Pure Tungsten'], ARRAY['refractory', 'highest-melting', 'high-density'],
  '350 HB', 350, NULL, NULL, 19.3, 3410, 980, 750,
  'W-99.9W', 'Body-centered cubic tungsten',
  'metal', 'very-hard', false, false, 'medium',
  'Annealed', 1400,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Hydrofluoric acid solution or electrolytic etching',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['HF Solution', 'Electrolytic'],
  ARRAY['Electronics', 'Lighting', 'Aerospace'], ARRAY['Light bulb filaments', 'Electronics', 'Aerospace components'], 'Refractory metal with the highest melting point of all pure metals. Used in lighting, electronics, and high-temperature applications.',
  'published', false, 94),

-- Tool Steels
('H13 Hot-Work Tool Steel', 'h13-hot-work-tool-steel', 'Tool Steel', ARRAY['H13', 'AISI H13', '1.2344'], ARRAY['hot-work', 'die-steel', 'chromium'],
  '192 HB', 192, NULL, NULL, 7.80, 1427, 1420, 1170,
  'Fe-0.40C-5Cr-1.5Mo-1V', 'Tempered martensite with carbides',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 1025,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Die casting', 'Forging', 'Extrusion'], ARRAY['Die casting dies', 'Extrusion dies', 'Hot forging dies'], 'Chromium hot-work tool steel with excellent hot hardness and thermal shock resistance. Most common hot-work die steel.',
  'published', true, 62),

('A2 Air-Hardening Tool Steel', 'a2-air-hardening-tool-steel', 'Tool Steel', ARRAY['A2', 'AISI A2', '1.2363'], ARRAY['cold-work', 'air-hardening', 'medium-alloy'],
  '248 HB', 248, NULL, NULL, 7.86, 1420, 760, 620,
  'Fe-1.0C-5Cr-1Mo', 'Tempered martensite with carbides',
  'alloy', 'very-hard', false, true, 'low',
  'Air quenched and tempered', 925,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Dies', 'Molds', 'Cutting tools'], ARRAY['Blanking dies', 'Forming dies', 'Shear blades'], 'Air-hardening tool steel with good dimensional stability. Used for dies and molds.',
  'published', false, 63),

('O1 Oil-Hardening Tool Steel', 'o1-oil-hardening-tool-steel', 'Tool Steel', ARRAY['O1', 'AISI O1', '1.2510'], ARRAY['cold-work', 'oil-hardening', 'general-purpose'],
  '217 HB', 217, NULL, NULL, 7.81, 1420, 760, 620,
  'Fe-0.90C-1.0Mn-0.5Cr-0.5W', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Oil quenched and tempered', 790,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or 4% picral',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Cutting tools', 'Dies', 'Gauges'], ARRAY['Cutting tools', 'Punches', 'Gauges'], 'Oil-hardening tool steel with good machinability. General-purpose tool steel for cold-work applications.',
  'published', false, 64),

('S7 Shock-Resisting Tool Steel', 's7-shock-resisting-tool-steel', 'Tool Steel', ARRAY['S7', 'AISI S7', '1.2363'], ARRAY['shock-resisting', 'toughness', 'impact'],
  '197 HB', 197, NULL, NULL, 7.83, 1420, 1720, 1380,
  'Fe-0.50C-3.25Cr-1.4Mo-0.4V', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Air quenched and tempered', 955,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Chisels', 'Hammers', 'Punches'], ARRAY['Chisels', 'Hammers', 'Impact tools'], 'Shock-resisting tool steel with excellent toughness and impact resistance. Used for impact tools.',
  'published', false, 65),

('T1 High-Speed Steel', 't1-high-speed-steel', 'Tool Steel', ARRAY['T1', 'AISI T1', '18-4-1'], ARRAY['high-speed-steel', 'tungsten', 'cutting-tools'],
  '255 HB', 255, NULL, NULL, 8.67, 1420, 760, 620,
  'Fe-0.75C-18W-4Cr-1V', 'Martensite with complex carbides',
  'alloy', 'very-hard', false, true, 'low',
  'Quenched and tempered', 1275,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Cutting tools', 'Drills', 'End mills'], ARRAY['Cutting tools', 'Drill bits', 'Milling cutters'], 'Tungsten high-speed steel with excellent hot hardness. Classic high-speed steel composition.',
  'published', false, 66),

-- Stainless Steels
('420 Stainless Steel', '420-stainless-steel', 'Stainless Steel', ARRAY['420', 'AISI 420', 'EN 1.4021'], ARRAY['martensitic', 'hardenable', 'cutlery'],
  '217 HB', 217, NULL, NULL, 7.7, 1450, 655, 345,
  'Fe-13Cr-0.15C', 'Martensite (quenched), tempered martensite',
  'alloy', 'medium', false, true, 'medium',
  'Quenched and tempered', 980,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Vilella''s reagent or 2% nital',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Vilella''s Reagent', '2% Nital'],
  ARRAY['Cutlery', 'Surgical instruments', 'Valves'], ARRAY['Knives', 'Surgical instruments', 'Valves'], 'Martensitic stainless steel commonly used for cutlery and surgical instruments. Can be hardened by heat treatment.',
  'published', true, 17),

('440C Stainless Steel', '440c-stainless-steel', 'Stainless Steel', ARRAY['440C', 'AISI 440C', 'EN 1.4125'], ARRAY['martensitic', 'high-carbon', 'hard'],
  '255 HB', 255, NULL, NULL, 7.7, 1480, 760, 450,
  'Fe-17Cr-1.0C-1Mo', 'Martensite with primary carbides',
  'alloy', 'very-hard', false, true, 'medium',
  'Quenched and tempered', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Vilella''s reagent or 2% nital',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Vilella''s Reagent', '2% Nital'],
  ARRAY['Bearings', 'Cutlery', 'Valves'], ARRAY['Ball bearings', 'Knives', 'Valves'], 'High-carbon martensitic stainless steel with excellent hardness and wear resistance. Used for bearings and high-quality cutlery.',
  'published', true, 18),

('347 Stainless Steel', '347-stainless-steel', 'Stainless Steel', ARRAY['347', 'AISI 347', 'EN 1.4550'], ARRAY['austenitic', 'stabilized', 'welded'],
  '160 HB', 160, NULL, NULL, 8.0, 1400, 515, 205,
  'Fe-18Cr-11Ni-0.08C-0.8Nb', 'Austenite with NbC particles',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed at 1050-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia for 10-30 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Aqua Regia'],
  ARRAY['Welded structures', 'High-temperature', 'Chemical processing'], ARRAY['Welded structures', 'Heat exchangers', 'Pressure vessels'], 'Niobium-stabilized austenitic stainless steel for welded structures and high-temperature applications.',
  'published', false, 19),

-- Carbon and Alloy Steels
('AISI 1020 Carbon Steel', 'aisi-1020-carbon-steel', 'Carbon Steel', ARRAY['1020', 'C1020', 'SAE 1020'], ARRAY['low-carbon', 'machinable', 'general-purpose'],
  '111 HB', 111, NULL, NULL, 7.87, 1510, 380, 205,
  'Fe-0.20C-0.50Mn-0.04P-0.05S', 'Ferrite and pearlite',
  'alloy', 'soft', false, true, 'low',
  'Normalized or annealed', 870,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['General construction', 'Machinery', 'Automotive'], ARRAY['Shafts', 'Bolts', 'General parts'], 'Low carbon steel with good machinability and weldability. Very common general-purpose steel.',
  'published', false, 7),

('AISI 1035 Carbon Steel', 'aisi-1035-carbon-steel', 'Carbon Steel', ARRAY['1035', 'C1035', 'SAE 1035'], ARRAY['medium-carbon', 'heat-treatable', 'general-purpose'],
  '149 HB', 149, NULL, NULL, 7.87, 1500, 570, 310,
  'Fe-0.35C-0.75Mn-0.04P-0.05S', 'Ferrite and pearlite',
  'alloy', 'soft', false, true, 'low',
  'Normalized, quenched and tempered', 845,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Shafts', 'Gears', 'Bolts'], ARRAY['Shafts', 'Gears', 'Machine parts'], 'Medium carbon steel with good strength and machinability. Can be heat treated for improved properties.',
  'published', false, 8),

('5160 Spring Steel', '5160-spring-steel', 'Alloy Steel', ARRAY['5160', 'AISI 5160', '60Cr4'], ARRAY['spring-steel', 'chromium', 'high-strength'],
  '217 HB', 217, NULL, NULL, 7.85, 1480, 760, 415,
  'Fe-0.60C-0.85Mn-0.8Cr', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 845,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Springs', 'Automotive', 'Tools'], ARRAY['Coil springs', 'Leaf springs', 'Hand tools'], 'Chromium spring steel with excellent fatigue resistance and toughness. Used for springs and high-stress applications.',
  'published', true, 9),

('52100 Bearing Steel', '52100-bearing-steel', 'Alloy Steel', ARRAY['52100', 'AISI 52100', '100Cr6'], ARRAY['bearing-steel', 'high-carbon', 'chromium'],
  '197 HB', 197, NULL, NULL, 7.81, 1420, 760, 450,
  'Fe-1.0C-1.5Cr-0.35Mn', 'Tempered martensite with carbides',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 790,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or 4% picral',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Bearings', 'Races', 'Rollers'], ARRAY['Ball bearings', 'Roller bearings', 'Bearing races'], 'High-carbon chromium bearing steel with excellent hardness and wear resistance. Standard material for ball and roller bearings.',
  'published', true, 10),

-- Aluminum Alloys
('1100 Aluminum', '1100-aluminum', 'Aluminum Alloy', ARRAY['1100', 'AA1100', 'Pure Aluminum'], ARRAY['pure-aluminum', 'non-heat-treatable', 'electrical'],
  '23 HB', 23, NULL, NULL, 2.71, 643, 90, 35,
  'Al-99.0Al-0.12Cu', 'Alpha aluminum',
  'metal', 'soft', true, false, 'high',
  'Annealed', 345,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Electrical', 'Food processing', 'General fabrication'], ARRAY['Electrical conductors', 'Food containers', 'Sheet metal'], 'Commercially pure aluminum with excellent electrical conductivity and corrosion resistance. Used in electrical and food applications.',
  'published', false, 27),

('3004 Aluminum', '3004-aluminum', 'Aluminum Alloy', ARRAY['3004', 'AA3004', 'AlMn1Mg1'], ARRAY['non-heat-treatable', 'can-stock', 'general-purpose'],
  '45 HB', 45, NULL, NULL, 2.72, 643, 180, 69,
  'Al-1.2Mn-1.0Mg', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'medium',
  'As fabricated or strain hardened', 345,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Packaging', 'General fabrication'], ARRAY['Beverage cans', 'Sheet metal', 'General fabrication'], 'Non-heat-treatable aluminum-magnesium-manganese alloy. Commonly used for beverage cans and general fabrication.',
  'published', false, 28),

('2011 Aluminum', '2011-aluminum', 'Aluminum Alloy', ARRAY['2011', 'AA2011', 'AlCu6BiPb'], ARRAY['free-cutting', 'machinable', 'copper-alloy'],
  '95 HB', 95, NULL, NULL, 2.83, 540, 310, 165,
  'Al-5.5Cu-0.4Bi-0.4Pb', 'Alpha aluminum with Cu-Mg precipitates and lead particles',
  'alloy', 'soft', true, false, 'low',
  'Solution treated and aged (T6 temper)', 510,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Machining', 'Screws', 'Fasteners'], ARRAY['Screws', 'Nuts', 'Machined parts'], 'Free-cutting aluminum-copper alloy with excellent machinability. Used for high-volume machined parts.',
  'published', false, 29),

('2017 Aluminum', '2017-aluminum', 'Aluminum Alloy', ARRAY['2017', 'AA2017', 'AlCu4MgSi'], ARRAY['heat-treatable', 'high-strength', 'rivets'],
  '105 HB', 105, NULL, NULL, 2.79, 510, 427, 276,
  'Al-4Cu-0.6Mg-0.5Si', 'Alpha aluminum with Cu-Mg precipitates',
  'alloy', 'soft', true, false, 'low',
  'Solution treated and aged (T6 temper)', 500,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Rivets', 'Fasteners'], ARRAY['Aircraft rivets', 'Fasteners', 'Structural components'], 'High-strength aluminum-copper alloy. Historically used for aircraft rivets and structural applications.',
  'published', false, 30),

-- Copper Alloys
('C46400 Naval Brass', 'c46400-naval-brass', 'Copper Alloy', ARRAY['C46400', 'Naval Brass', '64-1-1 Brass'], ARRAY['brass', 'marine', 'corrosion-resistant'],
  '95 HB', 95, NULL, NULL, 8.41, 900, 380, 125,
  'Cu-39Zn-1Sn-0.5Pb', 'Alpha brass with some beta phase',
  'alloy', 'soft', true, false, 'high',
  'Annealed', 425,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Marine', 'Hardware', 'Fasteners'], ARRAY['Marine hardware', 'Fasteners', 'Propeller shafts'], 'Tin-bearing brass with excellent corrosion resistance in seawater. Used extensively in marine applications.',
  'published', true, 37),

('C51000 Phosphor Bronze', 'c51000-phosphor-bronze', 'Copper Alloy', ARRAY['C51000', 'Phosphor Bronze', '5% Tin Bronze'], ARRAY['bronze', 'spring', 'wear-resistant'],
  '78 HB', 78, NULL, NULL, 8.86, 1000, 380, 125,
  'Cu-5Sn-0.2P', 'Alpha copper with tin-rich phase',
  'alloy', 'soft', true, false, 'high',
  'Annealed', 425,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Springs', 'Bearings', 'Electrical'], ARRAY['Springs', 'Bearings', 'Electrical contacts'], 'Phosphor bronze with excellent spring properties and wear resistance. Used for springs and electrical contacts.',
  'published', false, 38),

-- Cast Irons
('Malleable Cast Iron', 'malleable-cast-iron', 'Cast Iron', ARRAY['Malleable Iron', 'Nodular Graphite Iron'], ARRAY['cast-iron', 'graphite', 'ductile'],
  '163 HB', 163, NULL, NULL, 7.2, 1150, 345, 207,
  'Fe-2.5C-1.0Si-0.5Mn', 'Ferrite or pearlite matrix with temper carbon nodules',
  'alloy', 'soft', false, true, 'low',
  'Annealed (malleabilized)', 900,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Hardware', 'Pipes'], ARRAY['Automotive parts', 'Pipe fittings', 'Hardware'], 'Cast iron heat treated to produce temper carbon nodules, providing improved ductility compared to gray iron.',
  'published', false, 73),

-- Nickel Alloys
('Inconel 600', 'inconel-600', 'Nickel Alloy', ARRAY['IN600', 'UNS N06600', 'Alloy 600'], ARRAY['nickel-base', 'corrosion-resistant', 'high-temperature'],
  '126 HB', 126, NULL, NULL, 8.47, 1371, 550, 240,
  'Ni-15.5Cr-8Fe-0.08C', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Heat treatment', 'Nuclear'], ARRAY['Heat treatment equipment', 'Chemical reactors', 'Nuclear reactors'], 'Nickel-chromium alloy with excellent corrosion resistance and high-temperature strength. Used in heat treatment and chemical processing.',
  'published', false, 56),

('Incoloy 800', 'incoloy-800', 'Nickel Alloy', ARRAY['Incoloy 800', 'UNS N08800', 'Alloy 800'], ARRAY['nickel-iron', 'high-temperature', 'corrosion-resistant'],
  '150 HB', 150, NULL, NULL, 8.0, 1380, 515, 205,
  'Ni-21Cr-32Fe-0.4Ti-0.4Al', 'Austenite with gamma prime',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Heat treatment', 'Chemical processing', 'Power generation'], ARRAY['Heat treatment equipment', 'Furnace components', 'Heat exchangers'], 'Nickel-iron-chromium alloy with excellent high-temperature strength and oxidation resistance. Used in heat treatment and power generation.',
  'published', false, 57);

-- Update slugs using the generate_material_slug function
UPDATE materials SET slug = generate_material_slug(name) WHERE slug IS NULL;

