-- Seed additional materials to reach exactly 120 total materials
-- This migration adds 43 high-priority materials commonly used in metallography

INSERT INTO materials (
  name, slug, category, alternative_names, tags,
  hardness, hardness_hb, hardness_hrc, hardness_hv, density, melting_point_celsius,
  tensile_strength_mpa, yield_strength_mpa,
  composition, microstructure,
  material_type, hardness_category, work_hardening, magnetic, corrosion_resistance,
  heat_treatment, annealing_temperature_celsius,
  sectioning_notes, mounting_notes, grinding_notes, polishing_notes, etching_notes,
  recommended_grinding_sequence, recommended_polishing_sequence,
  common_etchants,
  applications, typical_uses, detailed_description,
  status, featured, sort_order
) VALUES

-- Stainless Steels
('309 Stainless Steel', '309-stainless-steel', 'Stainless Steel', ARRAY['309', 'AISI 309', 'EN 1.4828'], ARRAY['austenitic', 'high-temperature', 'heat-resistant'],
  '217 HB', 217, NULL, NULL, 7.98, 1450, 515, 205,
  'Fe-23Cr-13Ni-0.08C', 'Austenite',
  'alloy', 'medium', true, false, 'excellent',
  'Solution annealed at 1050-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia for 10-30 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Aqua Regia'],
  ARRAY['Heat treatment', 'Furnaces', 'High-temperature'], ARRAY['Furnace components', 'Heat treatment equipment', 'Kiln furniture'], 'High-temperature austenitic stainless steel with excellent oxidation resistance. Used in heat treatment and furnace applications.',
  'published', false, 20),

('310 Stainless Steel', '310-stainless-steel', 'Stainless Steel', ARRAY['310', 'AISI 310', 'EN 1.4841'], ARRAY['austenitic', 'high-temperature', 'heat-resistant'],
  '217 HB', 217, NULL, NULL, 7.98, 1450, 515, 205,
  'Fe-25Cr-20Ni-0.08C', 'Austenite',
  'alloy', 'medium', true, false, 'excellent',
  'Solution annealed at 1050-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia for 10-30 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Aqua Regia'],
  ARRAY['Heat treatment', 'Furnaces', 'High-temperature'], ARRAY['Furnace components', 'Heat treatment equipment', 'Kiln furniture'], 'High-temperature austenitic stainless steel with superior oxidation resistance. Used in extreme temperature applications.',
  'published', false, 21),

('904L Super Austenitic Stainless Steel', '904l-super-austenitic-stainless-steel', 'Stainless Steel', ARRAY['904L', 'UNS N08904', 'EN 1.4539'], ARRAY['super-austenitic', 'corrosion-resistant', 'chemical'],
  '160 HB', 160, NULL, NULL, 8.0, 1350, 490, 220,
  'Fe-20Cr-25Ni-4.5Mo-1.5Cu-0.02C', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed at 1100-1150°C', 1125,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Pharmaceutical', 'Marine'], ARRAY['Chemical reactors', 'Heat exchangers', 'Marine equipment'], 'Super austenitic stainless steel with exceptional corrosion resistance, especially to sulfuric acid. Used in aggressive chemical environments.',
  'published', true, 22),

('15-5 PH Stainless Steel', '15-5-ph-stainless-steel', 'Stainless Steel', ARRAY['15-5 PH', 'AISI 630', 'UNS S15500'], ARRAY['precipitation-hardening', 'high-strength', 'aerospace'],
  '363 HB', 363, 40, NULL, 7.8, 1400, 1310, 1170,
  'Fe-15Cr-4.5Ni-3.5Cu-0.07C', 'Martensite with Cu-rich precipitates',
  'alloy', 'very-hard', false, true, 'high',
  'Solution treated and aged', 1040,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Aerospace', 'Defense', 'Medical'], ARRAY['Aircraft components', 'Medical devices', 'Defense applications'], 'Precipitation-hardening stainless steel with excellent strength and corrosion resistance. Similar to 17-4 PH but with improved properties.',
  'published', false, 23),

('2507 Super Duplex Stainless Steel', '2507-super-duplex-stainless-steel', 'Stainless Steel', ARRAY['2507', 'UNS S32750', 'Super Duplex'], ARRAY['super-duplex', 'corrosion-resistant', 'high-strength'],
  '310 HB', 310, 32, NULL, 7.8, 1420, 795, 550,
  'Fe-25Cr-7Ni-4Mo-0.03C-0.27N', 'Austenite and ferrite (approximately 50/50)',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution annealed at 1020-1100°C', 1050,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Beraha''s reagent or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Beraha''s Reagent', 'Electrolytic 10% Oxalic'],
  ARRAY['Offshore', 'Chemical processing', 'Desalination'], ARRAY['Offshore platforms', 'Heat exchangers', 'Desalination plants'], 'Super duplex stainless steel with very high strength and excellent corrosion resistance. Used in demanding offshore and chemical applications.',
  'published', true, 24),

-- Aluminum Alloys
('5056 Aluminum', '5056-aluminum', 'Aluminum Alloy', ARRAY['5056', 'AA5056', 'AlMg5'], ARRAY['non-heat-treatable', 'marine', 'weldable'],
  '65 HB', 65, NULL, NULL, 2.64, 568, 290, 152,
  'Al-5.2Mg-0.12Cr-0.1Mn', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'excellent',
  'As fabricated', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Marine', 'Wire', 'Fasteners'], ARRAY['Marine hardware', 'Wire', 'Rivets'], 'High-magnesium aluminum alloy with excellent corrosion resistance in marine environments. Used for marine hardware and wire.',
  'published', false, 31),

('5086 Aluminum', '5086-aluminum', 'Aluminum Alloy', ARRAY['5086', 'AA5086', 'AlMg4Mn'], ARRAY['non-heat-treatable', 'marine', 'weldable'],
  '70 HB', 70, NULL, NULL, 2.66, 574, 290, 124,
  'Al-4.0Mg-0.4Mn-0.15Cr', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'excellent',
  'As fabricated', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Marine', 'Pressure vessels', 'Cryogenic'], ARRAY['Marine structures', 'Pressure vessels', 'Cryogenic tanks'], 'Aluminum-magnesium alloy with excellent corrosion resistance and weldability. Used in marine and cryogenic applications.',
  'published', false, 32),

('5454 Aluminum', '5454-aluminum', 'Aluminum Alloy', ARRAY['5454', 'AA5454', 'AlMg3Mn'], ARRAY['non-heat-treatable', 'general-purpose', 'weldable'],
  '62 HB', 62, NULL, NULL, 2.69, 602, 250, 110,
  'Al-2.7Mg-0.8Mn-0.12Cr', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'high',
  'As fabricated', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['General fabrication', 'Pressure vessels'], ARRAY['Pressure vessels', 'Tanks', 'General fabrication'], 'Aluminum-magnesium-manganese alloy with good strength and corrosion resistance. Used in general fabrication and pressure vessels.',
  'published', false, 33),

('5456 Aluminum', '5456-aluminum', 'Aluminum Alloy', ARRAY['5456', 'AA5456', 'AlMg5Mn'], ARRAY['non-heat-treatable', 'marine', 'high-strength'],
  '90 HB', 90, NULL, NULL, 2.66, 568, 310, 160,
  'Al-5.1Mg-0.8Mn-0.12Cr', 'Alpha aluminum solid solution',
  'alloy', 'soft', true, false, 'excellent',
  'As fabricated', NULL,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Marine', 'Aerospace', 'Military'], ARRAY['Marine structures', 'Aircraft components', 'Military applications'], 'High-strength aluminum-magnesium alloy with excellent corrosion resistance. Used in marine and aerospace applications.',
  'published', false, 34),

('6005 Aluminum', '6005-aluminum', 'Aluminum Alloy', ARRAY['6005', 'AA6005', 'AlMgSi0.5'], ARRAY['heat-treatable', 'extrusion', 'general-purpose'],
  '95 HB', 95, NULL, NULL, 2.70, 582, 290, 240,
  'Al-0.6Mg-0.5Si', 'Alpha aluminum with Mg2Si precipitates',
  'alloy', 'soft', true, false, 'medium',
  'Solution treated and aged (T6 temper)', 530,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Extrusions', 'Automotive', 'General fabrication'], ARRAY['Extruded profiles', 'Automotive parts', 'General fabrication'], 'Heat-treatable aluminum-magnesium-silicon alloy commonly used for extrusions. Good strength and formability.',
  'published', false, 35),

('6063 Aluminum', '6063-aluminum', 'Aluminum Alloy', ARRAY['6063', 'AA6063', 'AlMg0.7Si'], ARRAY['heat-treatable', 'extrusion', 'architectural'],
  '73 HB', 73, NULL, NULL, 2.70, 615, 186, 145,
  'Al-0.7Mg-0.4Si', 'Alpha aluminum with Mg2Si precipitates',
  'alloy', 'soft', true, false, 'medium',
  'Solution treated and aged (T6 temper)', 530,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Architecture', 'Extrusions', 'General fabrication'], ARRAY['Window frames', 'Extruded profiles', 'Architectural components'], 'Heat-treatable aluminum-magnesium-silicon alloy with excellent extrudability. Most common architectural aluminum alloy.',
  'published', true, 36),

('6082 Aluminum', '6082-aluminum', 'Aluminum Alloy', ARRAY['6082', 'AA6082', 'AlMg1Si1'], ARRAY['heat-treatable', 'general-purpose', 'weldable'],
  '95 HB', 95, NULL, NULL, 2.70, 582, 310, 260,
  'Al-1.0Mg-1.0Si-0.7Mn', 'Alpha aluminum with Mg2Si precipitates',
  'alloy', 'soft', true, false, 'medium',
  'Solution treated and aged (T6 temper)', 530,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['General fabrication', 'Automotive', 'Marine'], ARRAY['General fabrication', 'Automotive parts', 'Marine hardware'], 'Heat-treatable aluminum-magnesium-silicon alloy with good strength and weldability. Common European alloy.',
  'published', false, 37),

('7050 Aluminum', '7050-aluminum', 'Aluminum Alloy', ARRAY['7050', 'AA7050', 'AlZn6CuMgZr'], ARRAY['high-strength', 'aerospace', 'heat-treatable'],
  '150 HB', 150, NULL, NULL, 2.83, 490, 524, 455,
  'Al-6.2Zn-2.3Cu-2.2Mg-0.12Zr', 'Alpha aluminum with Zn-Mg-Cu precipitates',
  'alloy', 'medium', true, false, 'medium',
  'Solution treated and aged (T74 temper)', 477,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Military'], ARRAY['Aircraft structures', 'Military aircraft', 'High-stress components'], 'High-strength aluminum-zinc-copper alloy with excellent stress-corrosion cracking resistance. Used in aerospace applications.',
  'published', true, 38),

('7475 Aluminum', '7475-aluminum', 'Aluminum Alloy', ARRAY['7475', 'AA7475', 'AlZn5.7MgCu'], ARRAY['high-strength', 'aerospace', 'heat-treatable'],
  '150 HB', 150, NULL, NULL, 2.81, 477, 524, 462,
  'Al-5.7Zn-1.6Cu-2.2Mg-0.22Cr', 'Alpha aluminum with Zn-Mg-Cu precipitates',
  'alloy', 'medium', true, false, 'medium',
  'Solution treated and aged (T76 temper)', 477,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Keller''s reagent for 10-20 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Keller''s Reagent', '0.5% HF'],
  ARRAY['Aerospace', 'Military'], ARRAY['Aircraft structures', 'Military aircraft', 'High-stress components'], 'High-strength aluminum-zinc-copper alloy with improved toughness. Used in critical aerospace applications.',
  'published', false, 39),

-- Tool Steels
('H11 Hot-Work Tool Steel', 'h11-hot-work-tool-steel', 'Tool Steel', ARRAY['H11', 'AISI H11', '1.2343'], ARRAY['hot-work', 'die-steel', 'chromium'],
  '192 HB', 192, NULL, NULL, 7.80, 1427, 1420, 1170,
  'Fe-0.40C-5Cr-1.5Mo-0.4V', 'Tempered martensite with carbides',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 1025,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Die casting', 'Forging', 'Extrusion'], ARRAY['Die casting dies', 'Extrusion dies', 'Hot forging dies'], 'Chromium hot-work tool steel with excellent hot hardness. Similar to H13 but with slightly different properties.',
  'published', false, 67),

('H21 Hot-Work Tool Steel', 'h21-hot-work-tool-steel', 'Tool Steel', ARRAY['H21', 'AISI H21', '1.2581'], ARRAY['hot-work', 'tungsten', 'die-steel'],
  '217 HB', 217, NULL, NULL, 8.00, 1420, 760, 620,
  'Fe-0.30C-3.5Cr-9W-0.5V', 'Tempered martensite with carbides',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 1200,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Die casting', 'Forging', 'Hot-work'], ARRAY['Die casting dies', 'Hot forging dies', 'Extrusion dies'], 'Tungsten hot-work tool steel with excellent hot hardness and wear resistance. Used for high-temperature die applications.',
  'published', false, 68),

('A4 Air-Hardening Tool Steel', 'a4-air-hardening-tool-steel', 'Tool Steel', ARRAY['A4', 'AISI A4', '1.2362'], ARRAY['cold-work', 'air-hardening', 'medium-alloy'],
  '248 HB', 248, NULL, NULL, 7.86, 1420, 760, 620,
  'Fe-1.0C-2Cr-1Mo-1Mn', 'Tempered martensite with carbides',
  'alloy', 'very-hard', false, true, 'low',
  'Air quenched and tempered', 925,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Dies', 'Molds', 'Cutting tools'], ARRAY['Blanking dies', 'Forming dies', 'Shear blades'], 'Air-hardening tool steel with good dimensional stability. Lower alloy content than A2.',
  'published', false, 69),

('A6 Air-Hardening Tool Steel', 'a6-air-hardening-tool-steel', 'Tool Steel', ARRAY['A6', 'AISI A6', '1.2363'], ARRAY['cold-work', 'air-hardening', 'medium-alloy'],
  '217 HB', 217, NULL, NULL, 7.83, 1420, 760, 620,
  'Fe-0.70C-1Cr-1Mo-2Mn', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Air quenched and tempered', 790,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Dies', 'Molds', 'Gauges'], ARRAY['Blanking dies', 'Forming dies', 'Gauges'], 'Air-hardening tool steel with good machinability. Lower carbon content for improved toughness.',
  'published', false, 70),

('S1 Shock-Resisting Tool Steel', 's1-shock-resisting-tool-steel', 'Tool Steel', ARRAY['S1', 'AISI S1', '1.2550'], ARRAY['shock-resisting', 'toughness', 'impact'],
  '197 HB', 197, NULL, NULL, 7.83, 1420, 1720, 1380,
  'Fe-0.50C-1.5Cr-2.5W-0.4V', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Oil quenched and tempered', 955,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Chisels', 'Hammers', 'Punches'], ARRAY['Chisels', 'Hammers', 'Impact tools'], 'Shock-resisting tool steel with excellent toughness. Tungsten-bearing for improved properties.',
  'published', false, 71),

('S5 Shock-Resisting Tool Steel', 's5-shock-resisting-tool-steel', 'Tool Steel', ARRAY['S5', 'AISI S5', '1.2363'], ARRAY['shock-resisting', 'toughness', 'impact'],
  '197 HB', 197, NULL, NULL, 7.83, 1420, 1720, 1380,
  'Fe-0.50C-0.8Cr-1Mo-0.4V', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Oil quenched and tempered', 955,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Chisels', 'Hammers', 'Punches'], ARRAY['Chisels', 'Hammers', 'Impact tools'], 'Shock-resisting tool steel with excellent toughness. Lower alloy content for cost-effective impact applications.',
  'published', false, 72),

('T15 High-Speed Steel', 't15-high-speed-steel', 'Tool Steel', ARRAY['T15', 'AISI T15', '1.3202'], ARRAY['high-speed-steel', 'tungsten', 'cutting-tools'],
  '255 HB', 255, NULL, NULL, 8.67, 1420, 760, 620,
  'Fe-1.5C-12W-5V-4Cr-5Co', 'Martensite with complex carbides',
  'alloy', 'very-hard', false, true, 'low',
  'Quenched and tempered', 1275,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Cutting tools', 'Drills', 'End mills'], ARRAY['Cutting tools', 'Drill bits', 'Milling cutters'], 'High-vanadium, high-cobalt high-speed steel with excellent hot hardness and wear resistance. Premium cutting tool material.',
  'published', false, 73),

('M42 High-Speed Steel', 'm42-high-speed-steel', 'Tool Steel', ARRAY['M42', 'AISI M42', '1.3247'], ARRAY['high-speed-steel', 'cobalt', 'cutting-tools'],
  '262 HB', 262, NULL, NULL, 8.10, 1420, 760, 620,
  'Fe-1.1C-9.5Mo-1.5W-4Cr-1.1V-8Co', 'Martensite with complex carbides',
  'alloy', 'very-hard', false, true, 'low',
  'Quenched and tempered', 1220,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital or Vilella''s reagent',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', 'Vilella''s Reagent'],
  ARRAY['Cutting tools', 'Drills', 'End mills'], ARRAY['Cutting tools', 'Drill bits', 'Milling cutters'], 'Cobalt-bearing high-speed steel with excellent hot hardness. Used for high-performance cutting tools.',
  'published', false, 74),

-- Nickel Alloys
('Inconel 601', 'inconel-601', 'Nickel Alloy', ARRAY['IN601', 'UNS N06601', 'Alloy 601'], ARRAY['nickel-base', 'corrosion-resistant', 'high-temperature'],
  '150 HB', 150, NULL, NULL, 8.10, 1371, 655, 240,
  'Ni-23Cr-14Fe-1.4Al-0.08C', 'Austenite with gamma prime',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Heat treatment', 'Chemical processing', 'Power generation'], ARRAY['Heat treatment equipment', 'Furnace components', 'Heat exchangers'], 'Nickel-chromium-iron alloy with excellent high-temperature strength and oxidation resistance. Used in heat treatment and power generation.',
  'published', false, 58),

('Inconel 617', 'inconel-617', 'Nickel Alloy', ARRAY['IN617', 'UNS N06617', 'Alloy 617'], ARRAY['superalloy', 'high-temperature', 'nickel-base'],
  '150 HB', 150, NULL, NULL, 8.36, 1330, 655, 240,
  'Ni-22Cr-12.5Co-9Mo-1.2Al-0.07C', 'Austenite with gamma prime',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1175,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Gas turbines', 'Nuclear', 'Aerospace'], ARRAY['Gas turbine components', 'Nuclear reactors', 'Aerospace components'], 'Nickel-based superalloy with excellent high-temperature strength and creep resistance. Used in gas turbines and nuclear applications.',
  'published', true, 59),

('Inconel 690', 'inconel-690', 'Nickel Alloy', ARRAY['IN690', 'UNS N06690', 'Alloy 690'], ARRAY['nickel-base', 'corrosion-resistant', 'nuclear'],
  '150 HB', 150, NULL, NULL, 8.30, 1343, 550, 240,
  'Ni-30Cr-9Fe-0.02C', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Nuclear', 'Chemical processing', 'Power generation'], ARRAY['Nuclear reactors', 'Steam generators', 'Heat exchangers'], 'Nickel-chromium alloy with excellent corrosion resistance, especially to stress-corrosion cracking. Used extensively in nuclear applications.',
  'published', true, 60),

('Incoloy 825', 'incoloy-825', 'Nickel Alloy', ARRAY['Incoloy 825', 'UNS N08825', 'Alloy 825'], ARRAY['nickel-iron', 'corrosion-resistant', 'chemical'],
  '150 HB', 150, NULL, NULL, 8.14, 1377, 586, 241,
  'Ni-21.5Cr-30Fe-3Mo-2.3Cu-0.9Ti-0.6Al', 'Austenite with gamma prime',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Marine', 'Oil and gas'], ARRAY['Chemical reactors', 'Marine equipment', 'Oil and gas equipment'], 'Nickel-iron-chromium alloy with excellent corrosion resistance to sulfuric and phosphoric acids. Used in chemical processing.',
  'published', false, 61),

('Incoloy 925', 'incoloy-925', 'Nickel Alloy', ARRAY['Incoloy 925', 'UNS N09925', 'Alloy 925'], ARRAY['precipitation-hardening', 'corrosion-resistant', 'nickel-iron'],
  '310 HB', 310, 32, NULL, 8.14, 1377, 860, 690,
  'Ni-21Cr-30Fe-3Mo-2.3Cu-0.9Ti-0.6Al', 'Austenite with gamma prime precipitates',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Oil and gas', 'Chemical processing', 'Marine'], ARRAY['Oil and gas equipment', 'Chemical reactors', 'Marine equipment'], 'Precipitation-hardening nickel-iron alloy with excellent strength and corrosion resistance. Used in demanding oil and gas applications.',
  'published', false, 62),

-- Titanium Alloys
('Commercially Pure Titanium Grade 1', 'commercially-pure-titanium-grade-1', 'Titanium Alloy', ARRAY['CP Ti Grade 1', 'Grade 1', 'ASTM B265'], ARRAY['pure-titanium', 'corrosion-resistant', 'biomedical'],
  '115 HB', 115, NULL, NULL, 4.51, 1668, 240, 170,
  'Ti-0.2O-0.2Fe', 'Alpha titanium',
  'metal', 'soft', true, false, 'excellent',
  'Annealed', 700,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Chemical processing', 'Biomedical', 'Marine'], ARRAY['Chemical equipment', 'Medical implants', 'Heat exchangers'], 'Highest purity unalloyed titanium with excellent formability and corrosion resistance. Used in chemical processing and medical applications.',
  'published', false, 45),

('Commercially Pure Titanium Grade 3', 'commercially-pure-titanium-grade-3', 'Titanium Alloy', ARRAY['CP Ti Grade 3', 'Grade 3', 'ASTM B265'], ARRAY['pure-titanium', 'corrosion-resistant', 'biomedical'],
  '140 HB', 140, NULL, NULL, 4.51, 1668, 345, 275,
  'Ti-0.35O-0.3Fe', 'Alpha titanium',
  'metal', 'soft', true, false, 'excellent',
  'Annealed', 700,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Chemical processing', 'Biomedical', 'Marine'], ARRAY['Chemical equipment', 'Medical implants', 'Heat exchangers'], 'Medium-strength unalloyed titanium with good balance of strength and formability. Used in chemical processing and medical applications.',
  'published', false, 46),

('Commercially Pure Titanium Grade 4', 'commercially-pure-titanium-grade-4', 'Titanium Alloy', ARRAY['CP Ti Grade 4', 'Grade 4', 'ASTM B265'], ARRAY['pure-titanium', 'corrosion-resistant', 'biomedical'],
  '200 HB', 200, NULL, NULL, 4.51, 1668, 550, 483,
  'Ti-0.40O-0.5Fe', 'Alpha titanium',
  'metal', 'soft', true, false, 'excellent',
  'Annealed', 700,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Chemical processing', 'Biomedical', 'Marine'], ARRAY['Chemical equipment', 'Medical implants', 'Heat exchangers'], 'Highest strength unalloyed titanium with excellent corrosion resistance. Used in chemical processing and medical applications.',
  'published', false, 47),

('Ti-15V-3Cr-3Al-3Sn', 'ti-15v-3cr-3al-3sn', 'Titanium Alloy', ARRAY['Ti-15-3-3-3', 'Beta C'], ARRAY['beta-titanium', 'high-strength', 'aerospace'],
  '365 HB', 365, 38, NULL, 4.76, 1600, 1170, 1100,
  'Ti-15V-3Cr-3Al-3Sn', 'Beta titanium',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 815,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Kroll''s reagent for 5-15 seconds',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Kroll''s Reagent', 'Modified Kroll''s'],
  ARRAY['Aerospace', 'Medical'], ARRAY['Aircraft components', 'Medical implants'], 'Beta titanium alloy with very high strength. Used in demanding aerospace and medical applications.',
  'published', false, 48),

-- Carbon and Alloy Steels
('AISI 8620 Case-Hardening Steel', 'aisi-8620-case-hardening-steel', 'Alloy Steel', ARRAY['8620', 'AISI 8620', '20NiCrMo2'], ARRAY['case-hardening', 'nickel-chromium', 'automotive'],
  '149 HB', 149, NULL, NULL, 7.85, 1427, 655, 385,
  'Fe-0.20C-0.8Ni-0.5Cr-0.25Mo', 'Ferrite and pearlite',
  'alloy', 'soft', false, true, 'low',
  'Case hardened', 870,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Gears', 'Shafts'], ARRAY['Gears', 'Shafts', 'Automotive components'], 'Nickel-chromium-molybdenum case-hardening steel with excellent hardenability. Used for gears and automotive components.',
  'published', true, 11),

('AISI 9310 Case-Hardening Steel', 'aisi-9310-case-hardening-steel', 'Alloy Steel', ARRAY['9310', 'AISI 9310', '20NiCrMo3'], ARRAY['case-hardening', 'nickel-chromium', 'aerospace'],
  '197 HB', 197, NULL, NULL, 7.85, 1427, 1170, 795,
  'Fe-0.10C-3.25Ni-1.2Cr-0.12Mo', 'Ferrite and pearlite',
  'alloy', 'medium', false, true, 'low',
  'Case hardened', 870,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Aerospace', 'Gears', 'Shafts'], ARRAY['Aircraft gears', 'Shafts', 'High-stress components'], 'High-nickel case-hardening steel with excellent hardenability and toughness. Used in aerospace applications.',
  'published', false, 12),

('AISI 4130 Chromium-Molybdenum Steel', 'aisi-4130-chromium-molybdenum-steel', 'Alloy Steel', ARRAY['4130', 'AISI 4130', '25CrMo4'], ARRAY['heat-treatable', 'high-strength', 'aerospace'],
  '197 HB', 197, NULL, NULL, 7.85, 1416, 655, 415,
  'Fe-0.30C-1Cr-0.25Mo-0.85Mn', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 845,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Aerospace', 'Automotive', 'Oil and gas'], ARRAY['Aircraft structures', 'Automotive components', 'Oil and gas equipment'], 'Chromium-molybdenum steel with excellent strength and weldability. Used in aerospace and automotive applications.',
  'published', true, 13),

('AISI 6150 Chromium-Vanadium Steel', 'aisi-6150-chromium-vanadium-steel', 'Alloy Steel', ARRAY['6150', 'AISI 6150', '50CrV4'], ARRAY['spring-steel', 'chromium-vanadium', 'high-strength'],
  '217 HB', 217, NULL, NULL, 7.85, 1480, 760, 415,
  'Fe-0.50C-1Cr-0.15V-0.85Mn', 'Tempered martensite',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 845,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Springs', 'Automotive', 'Tools'], ARRAY['Coil springs', 'Leaf springs', 'Hand tools'], 'Chromium-vanadium spring steel with excellent fatigue resistance. Used for high-stress spring applications.',
  'published', false, 14),

-- Copper Alloys
('C86300 Manganese Bronze', 'c86300-manganese-bronze', 'Copper Alloy', ARRAY['C86300', 'Manganese Bronze', 'High-Strength Bronze'], ARRAY['bronze', 'high-strength', 'manganese'],
  '195 HB', 195, NULL, NULL, 7.6, 900, 655, 345,
  'Cu-25Zn-7Al-3Fe-3Mn', 'Alpha brass with beta phase and iron particles',
  'alloy', 'medium', false, false, 'medium',
  'As cast or heat treated', 600,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Marine', 'Bearings', 'Gears'], ARRAY['Propellers', 'Bearings', 'Gears'], 'High-strength manganese bronze with excellent wear resistance. Used in marine and bearing applications.',
  'published', false, 39),

('C90700 Tin Bronze', 'c90700-tin-bronze', 'Copper Alloy', ARRAY['C90700', '90-10 Bronze', 'Tin Bronze'], ARRAY['bronze', 'bearing', 'corrosion-resistant'],
  '70 HB', 70, NULL, NULL, 8.80, 1000, 240, 124,
  'Cu-10Sn', 'Alpha copper with tin-rich phase',
  'alloy', 'soft', true, false, 'high',
  'Annealed', 425,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 240 grit SiC, progress through 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Ammonium persulfate or ferric chloride',
  ARRAY['240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Ammonium Persulfate', 'Ferric Chloride'],
  ARRAY['Bearings', 'Bushings', 'Marine'], ARRAY['Bearings', 'Bushings', 'Marine hardware'], 'Tin bronze with excellent bearing properties and corrosion resistance. Used in bearing and marine applications.',
  'published', false, 40),

-- Cast Irons
('Compacted Graphite Iron', 'compacted-graphite-iron', 'Cast Iron', ARRAY['CGI', 'Vermicular Graphite Iron'], ARRAY['cast-iron', 'graphite', 'automotive'],
  '230 HB', 230, NULL, NULL, 7.1, 1150, 450, 320,
  'Fe-3.5C-2.5Si-0.5Mn-0.04Mg', 'Pearlite matrix with compacted graphite',
  'alloy', 'medium', false, true, 'low',
  'As cast', NULL,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Diesel engines'], ARRAY['Engine blocks', 'Cylinder heads', 'Diesel engines'], 'Cast iron with compacted graphite providing properties between gray and ductile iron. Used in modern diesel engines.',
  'published', true, 74),

('Austempered Ductile Iron', 'austempered-ductile-iron', 'Cast Iron', ARRAY['ADI', 'Austempered DI'], ARRAY['cast-iron', 'graphite', 'high-strength'],
  '310 HB', 310, 32, NULL, 7.1, 1150, 965, 655,
  'Fe-3.5C-2.5Si-0.5Mn-0.04Mg', 'Bainite matrix with spheroidal graphite',
  'alloy', 'very-hard', false, true, 'low',
  'Austempered', 900,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 10-20 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Gears', 'High-stress'], ARRAY['Gears', 'Crankshafts', 'High-stress components'], 'Heat-treated ductile iron with bainitic matrix providing very high strength. Used in high-stress automotive applications.',
  'published', true, 75),

-- Specialty Materials
('Hastelloy B-2', 'hastelloy-b-2', 'Nickel Alloy', ARRAY['Hastelloy B-2', 'UNS N10665', 'Alloy B-2'], ARRAY['nickel-molybdenum', 'corrosion-resistant', 'chemical'],
  '150 HB', 150, NULL, NULL, 9.22, 1330, 690, 315,
  'Ni-28Mo-0.01C', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1065,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Pharmaceutical'], ARRAY['Chemical reactors', 'Pharmaceutical equipment', 'Acid handling'], 'Nickel-molybdenum alloy with excellent resistance to reducing acids. Used in aggressive chemical environments.',
  'published', false, 63),

('Hastelloy C-22', 'hastelloy-c-22', 'Nickel Alloy', ARRAY['Hastelloy C-22', 'UNS N06022', 'Alloy C-22'], ARRAY['nickel-base', 'corrosion-resistant', 'chemical'],
  '150 HB', 150, NULL, NULL, 8.69, 1350, 690, 315,
  'Ni-22Cr-13Mo-3W-0.01C', 'Austenite',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1150,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Chemical processing', 'Pollution control', 'Pharmaceutical'], ARRAY['Chemical reactors', 'Scrubbers', 'Pharmaceutical equipment'], 'Nickel-chromium-molybdenum superalloy with outstanding corrosion resistance. Improved version of C-276.',
  'published', false, 64),

('Nimonic 80A', 'nimonic-80a', 'Nickel Alloy', ARRAY['Nimonic 80A', 'UNS N07080', 'N80A'], ARRAY['superalloy', 'high-temperature', 'nickel-base'],
  '310 HB', 310, 32, NULL, 8.19, 1320, 965, 690,
  'Ni-20Cr-2Ti-1.3Al-0.05C', 'Gamma matrix with gamma prime',
  'alloy', 'very-hard', false, false, 'excellent',
  'Solution treated and aged', 1080,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Gas turbines', 'Aerospace'], ARRAY['Gas turbine blades', 'Aerospace components'], 'Nickel-based superalloy with excellent high-temperature strength and creep resistance. Used in gas turbine applications.',
  'published', false, 65),

('Haynes 230', 'haynes-230', 'Nickel Alloy', ARRAY['Haynes 230', 'UNS N06230', 'Alloy 230'], ARRAY['superalloy', 'high-temperature', 'nickel-base'],
  '150 HB', 150, NULL, NULL, 8.97, 1330, 760, 310,
  'Ni-22Cr-14W-2Mo-0.1C-0.3Al-0.02La', 'Austenite with carbides',
  'alloy', 'soft', true, false, 'excellent',
  'Solution annealed', 1230,
  'Use slow-speed diamond saw with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', 'Glyceregia or electrolytic 10% oxalic acid',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['Glyceregia', 'Electrolytic 10% Oxalic'],
  ARRAY['Gas turbines', 'Heat treatment', 'Aerospace'], ARRAY['Gas turbine components', 'Furnace components', 'Aerospace components'], 'Nickel-based superalloy with excellent high-temperature strength and oxidation resistance. Used in gas turbines and heat treatment.',
  'published', false, 66);

-- Update slugs using the generate_material_slug function
UPDATE materials SET slug = generate_material_slug(name) WHERE slug IS NULL;

