-- Add one more material to reach exactly 120 total materials

-- First, delete if it exists with any slug variation
DELETE FROM materials WHERE name = 'AISI 4142 Chromium-Molybdenum Steel';

-- Insert the material (slug will be auto-generated by the function at the end)
INSERT INTO materials (
  name, slug, category, alternative_names, tags,
  hardness, hardness_hb, hardness_hrc, hardness_hv, density, melting_point_celsius,
  tensile_strength_mpa, yield_strength_mpa,
  composition, microstructure,
  material_type, hardness_category, work_hardening, magnetic, corrosion_resistance,
  heat_treatment, annealing_temperature_celsius,
  sectioning_notes, mounting_notes, grinding_notes, polishing_notes, etching_notes,
  recommended_grinding_sequence, recommended_polishing_sequence,
  common_etchants,
  applications, typical_uses, detailed_description,
  status, featured, sort_order
) VALUES
('AISI 4142 Chromium-Molybdenum Steel', generate_material_slug('AISI 4142 Chromium-Molybdenum Steel'), 'Alloy Steel', ARRAY['4142', 'AISI 4142', '42CrMo4'], ARRAY['heat-treatable', 'high-strength', 'machinable'],
  '217 HB', 217, NULL, NULL, 7.85, 1420, 655, 415,
  'Fe-0.42C-1Cr-0.2Mo', 'Ferrite and pearlite (normalized), tempered martensite (quenched and tempered)',
  'alloy', 'medium', false, true, 'low',
  'Quenched and tempered', 870,
  'Use abrasive cutoff wheel with coolant', 'Cold mounting with epoxy resin', 'Start with 120 grit SiC, progress through 240, 320, 400, 600', 'Use 6μm and 1μm diamond paste on napless cloth', '2% nital for 5-15 seconds',
  ARRAY['120', '240', '320', '400', '600'], ARRAY['6μm diamond', '1μm diamond'],
  ARRAY['2% Nital', '4% Picral'],
  ARRAY['Automotive', 'Machinery', 'General fabrication'], ARRAY['Shafts', 'Gears', 'Bolts'], 'Medium-carbon chromium-molybdenum steel with good hardenability and strength. Used in automotive and machinery applications.',
  'published', false, 50);

