-- Seed common etchants database
-- This includes the most commonly used etchants in metallography

INSERT INTO etchants (
  name, slug, alternative_names, tags, category,
  composition, concentration, ingredients,
  application_method, typical_time_seconds, temperature_celsius, voltage, current_density,
  reveals, typical_results, color_effects,
  compatible_materials, incompatible_materials,
  pace_product_available, pace_product_slug, pace_product_url,
  preparation_notes, application_notes, troubleshooting_notes, storage_notes,
  alternative_etchants, similar_etchants,
  astm_references, iso_references,
  status, featured, sort_order
) VALUES

-- Nital Series (Most Common)
('2% Nital', '2-percent-nital', ARRAY['2% Nitric Acid', 'Nital 2%'], ARRAY['carbon-steel', 'low-alloy-steel', 'general-purpose'], 'general-purpose',
  '2% Nitric Acid in Ethanol', '2%', 
  '[{"name": "Nitric Acid", "percentage": 2, "role": "etching agent"}, {"name": "Ethanol", "percentage": 98, "role": "solvent"}]'::jsonb,
  'immersion', 5, NULL, NULL, NULL,
  'Grain boundaries, ferrite, pearlite', 'Reveals ferrite grain boundaries and pearlite colonies. Darkens pearlite, leaves ferrite light.', 'Pearlite darkens, ferrite remains light',
  ARRAY['carbon-steel', 'low-alloy-steel', 'cast-iron'], ARRAY['stainless-steel', 'aluminum', 'titanium'],
  true, 'nital-2', NULL,
  'Mix 2 ml concentrated nitric acid (HNO₃) with 98 ml ethanol (95% or absolute). Add acid to ethanol slowly with stirring. Store in glass bottle.', 
  'Immerse sample for 5-15 seconds. Swab gently if needed. Rinse immediately with ethanol, then water. Dry with compressed air.',
  'If over-etched (too dark), reduce time or concentration. If under-etched, increase time slightly. Ensure fresh etchant for best results.',
  'Store in dark glass bottle with tight cap. Keep away from light. Shelf life: 3-6 months if properly stored.',
  ARRAY['3% Nital', '4% Picral'], ARRAY['3% Nital', '5% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 1),

('3% Nital', '3-percent-nital', ARRAY['3% Nitric Acid', 'Nital 3%'], ARRAY['carbon-steel', 'medium-carbon-steel', 'general-purpose'], 'general-purpose',
  '3% Nitric Acid in Ethanol', '3%',
  '[{"name": "Nitric Acid", "percentage": 3, "role": "etching agent"}, {"name": "Ethanol", "percentage": 97, "role": "solvent"}]'::jsonb,
  'immersion', 10, NULL, NULL, NULL,
  'Grain boundaries, ferrite, pearlite, bainite', 'Similar to 2% Nital but more aggressive. Better for harder steels and bainitic structures.', 'Pearlite darkens more, ferrite remains light',
  ARRAY['medium-carbon-steel', 'high-carbon-steel', 'tool-steel'], ARRAY['stainless-steel', 'aluminum'],
  true, 'nital-3', NULL,
  'Mix 3 ml concentrated nitric acid (HNO₃) with 97 ml ethanol. Add acid to ethanol slowly with stirring.',
  'Immerse sample for 10-20 seconds. More aggressive than 2% Nital. Rinse with ethanol then water.',
  'Use for harder steels that don''t respond well to 2% Nital. Reduce time if over-etching occurs.',
  'Store in dark glass bottle. Shelf life: 3-6 months.',
  ARRAY['2% Nital', '4% Picral'], ARRAY['2% Nital', '4% Nital', '5% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 2),

('4% Nital', '4-percent-nital', ARRAY['4% Nitric Acid', 'Nital 4%'], ARRAY['carbon-steel', 'medium-carbon-steel', 'general-purpose'], 'general-purpose',
  '4% Nitric Acid in Ethanol', '4%',
  '[{"name": "Nitric Acid", "percentage": 4, "role": "etching agent"}, {"name": "Ethanol", "percentage": 96, "role": "solvent"}]'::jsonb,
  'immersion', 12, NULL, NULL, NULL,
  'Grain boundaries, ferrite, pearlite, bainite', 'Intermediate concentration between 3% and 5% Nital. Good balance for medium-hardness steels.', 'Pearlite darkens, ferrite remains light',
  ARRAY['medium-carbon-steel', 'high-carbon-steel', 'tool-steel'], ARRAY['stainless-steel', 'aluminum'],
  false, NULL, NULL,
  'Mix 4 ml concentrated nitric acid (HNO₃) with 96 ml ethanol. Add acid to ethanol slowly with stirring.',
  'Immerse sample for 12-25 seconds. Intermediate aggressiveness between 3% and 5% Nital. Rinse with ethanol then water.',
  'Good intermediate option when 3% is too light and 5% is too aggressive. Adjust time based on material response.',
  'Store in dark glass bottle. Shelf life: 3-6 months.',
  ARRAY['3% Nital', '5% Nital'], ARRAY['3% Nital', '5% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 3),

('5% Nital', '5-percent-nital', ARRAY['5% Nitric Acid', 'Nital 5%'], ARRAY['high-carbon-steel', 'tool-steel', 'hard-steel'], 'general-purpose',
  '5% Nitric Acid in Ethanol', '5%',
  '[{"name": "Nitric Acid", "percentage": 5, "role": "etching agent"}, {"name": "Ethanol", "percentage": 95, "role": "solvent"}]'::jsonb,
  'immersion', 15, NULL, NULL, NULL,
  'Grain boundaries, martensite, bainite, carbides', 'More aggressive etchant for hard steels. Reveals martensite and bainite structures clearly.', 'Strong contrast between phases',
  ARRAY['high-carbon-steel', 'tool-steel', 'hardened-steel'], ARRAY['stainless-steel', 'soft-materials'],
  true, 'nital-5', NULL,
  'Mix 5 ml concentrated nitric acid with 95 ml ethanol. Add acid slowly to ethanol.',
  'Immerse for 15-30 seconds. More aggressive - use shorter times initially. Rinse thoroughly.',
  'Use for very hard steels. Monitor etching time carefully to avoid over-etching.',
  'Store in dark glass bottle. Shelf life: 3-6 months.',
  ARRAY['4% Nital', 'Vilella''s Reagent'], ARRAY['4% Nital', '8% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 4),

-- Picral (Alternative to Nital)
('4% Picral', '4-percent-picral', ARRAY['Picric Acid', 'Picral 4%'], ARRAY['carbon-steel', 'cast-iron', 'pearlite'], 'general-purpose',
  '4% Picric Acid in Ethanol', '4%',
  '[{"name": "Picric Acid", "percentage": 4, "role": "etching agent"}, {"name": "Ethanol", "percentage": 96, "role": "solvent"}]'::jsonb,
  'immersion', 10, NULL, NULL, NULL,
  'Pearlite, cementite, grain boundaries', 'Excellent for revealing pearlite structure. Does not attack ferrite grain boundaries as strongly as Nital.', 'Pearlite darkens, ferrite remains light',
  ARRAY['carbon-steel', 'cast-iron', 'pearlitic-steel'], ARRAY['stainless-steel', 'martensitic-steel'],
  true, 'picral', NULL,
  'Mix 4 g picric acid with 100 ml ethanol. Warm slightly to dissolve. CAUTION: Picric acid is explosive when dry.',
  'Immerse sample for 10-20 seconds. Swab if needed. Rinse with ethanol then water.',
  'Keep picric acid wet at all times. Never allow to dry. Store in water-wet condition.',
  'Store in dark bottle, keep wet. Add water if solution dries. Extremely hazardous when dry.',
  ARRAY['2% Nital', '3% Nital'], ARRAY['2% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 5),

-- Stainless Steel Etchants
('Kalling''s No. 2', 'kallings-no-2', ARRAY['Kallings 2', 'Kalling''s Reagent'], ARRAY['stainless-steel', 'austenitic', 'chromium-steel'], 'material-specific',
  '5g CuCl₂, 100ml HCl, 100ml Ethanol', 'Saturated',
  '[{"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "100ml", "role": "solvent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Austenite grain boundaries, sigma phase, carbides', 'Excellent for austenitic stainless steels. Reveals grain boundaries and secondary phases.', 'Grain boundaries dark, matrix light',
  ARRAY['stainless-steel', 'austenitic-stainless-steel', 'chromium-nickel-steel'], ARRAY['ferritic-steel', 'martensitic-steel'],
  true, 'kallings-no-2', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol. Mix thoroughly.',
  'Immerse sample for 30-60 seconds. May require swabbing. Rinse with water and ethanol.',
  'Works best on austenitic stainless steels. May over-etch if left too long.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Glyceregia', 'Aqua Regia'], ARRAY['Kallings No. 1'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 5),

('Glyceregia', 'glyceregia', ARRAY['Glycerol-HCl-HNO₃'], ARRAY['stainless-steel', 'nickel-alloy', 'high-temperature-alloy'], 'material-specific',
  '15ml HCl, 10ml HNO₃, 10ml Glycerol', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "15ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "10ml", "role": "etching agent"}, {"name": "Glycerol", "amount": "10ml", "role": "modifier"}]'::jsonb,
  'immersion', 20, NULL, NULL, NULL,
  'Grain boundaries, phases, carbides', 'Excellent for austenitic stainless steels and nickel alloys. Reveals grain structure clearly.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'nickel-alloy', 'inconel', 'hastelloy'], ARRAY['carbon-steel', 'aluminum'],
  false, NULL, NULL,
  'Mix 15ml HCl, 10ml HNO₃, and 10ml glycerol. Add acids to glycerol slowly. CAUTION: Exothermic reaction.',
  'Immerse sample for 20-40 seconds. Swab gently. Rinse immediately with water and ethanol.',
  'Prepare fresh for best results. Glycerol slows reaction rate. Use fume hood.',
  'Store in glass bottle. Prepare fresh when needed. Shelf life: 1-2 weeks.',
  ARRAY['Kalling''s No. 2', 'Aqua Regia'], ARRAY['Aqua Regia'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 6),

-- Titanium Etchants
('Kroll''s Reagent', 'krolls-reagent', ARRAY['Kroll''s Etchant'], ARRAY['titanium', 'titanium-alloy', 'zirconium'], 'material-specific',
  '2-3ml HF, 5ml HNO₃, 100ml H₂O', '2-3%',
  '[{"name": "Hydrofluoric Acid", "amount": "2-3ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "5ml", "role": "oxidizer"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'swabbing', 5, NULL, NULL, NULL,
  'Alpha-beta phases, grain boundaries', 'Standard etchant for titanium alloys. Reveals alpha and beta phases with good contrast.', 'Alpha phase light, beta phase dark',
  ARRAY['titanium', 'titanium-alloy', 'zirconium'], ARRAY['steel', 'aluminum'],
  true, 'krolls', NULL,
  'CAUTION: HF is extremely hazardous. Mix 2-3ml HF, 5ml HNO₃, and 100ml water in plastic container. Use fume hood and proper PPE.',
  'Swab sample for 5-15 seconds. Do not immerse. Rinse immediately with copious water.',
  'HF causes severe burns. Always use in fume hood with proper PPE. Have calcium gluconate gel available.',
  'Store in plastic container. Label clearly. Extremely hazardous - follow safety protocols.',
  ARRAY['Modified Kroll''s', 'Keller''s Reagent'], ARRAY['Modified Kroll''s'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 7),

-- Aluminum Etchants
('Keller''s Reagent', 'kellers-reagent', ARRAY['Keller''s Etchant'], ARRAY['aluminum', 'aluminum-alloy', 'magnesium'], 'material-specific',
  '2ml HF, 3ml HCl, 5ml HNO₃, 190ml H₂O', 'Mixed',
  '[{"name": "Hydrofluoric Acid", "amount": "2ml", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "3ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "5ml", "role": "oxidizer"}, {"name": "Water", "amount": "190ml", "role": "solvent"}]'::jsonb,
  'immersion', 15, NULL, NULL, NULL,
  'Grain boundaries, precipitates, phases', 'Standard etchant for aluminum alloys. Reveals grain structure and second phases.', 'Grain boundaries dark',
  ARRAY['aluminum', 'aluminum-alloy', 'magnesium'], ARRAY['steel', 'titanium'],
  true, 'kellers', NULL,
  'CAUTION: HF is extremely hazardous. Mix 2ml HF, 3ml HCl, 5ml HNO₃, and 190ml water in plastic container.',
  'Immerse sample for 10-20 seconds. Swab if needed. Rinse immediately with copious water.',
  'HF causes severe burns. Use in fume hood with proper PPE. Have calcium gluconate gel available.',
  'Store in plastic container. Label clearly. Extremely hazardous.',
  ARRAY['0.5% HF', 'Modified Keller''s'], ARRAY['0.5% HF'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 8),

-- Copper Alloy Etchants
('Ammonium Persulfate', 'ammonium-persulfate', ARRAY['(NH₄)₂S₂O₈'], ARRAY['copper', 'copper-alloy', 'brass', 'bronze'], 'material-specific',
  '10% (NH₄)₂S₂O₈ in H₂O', '10%',
  '[{"name": "Ammonium Persulfate", "percentage": 10, "role": "etching agent"}, {"name": "Water", "percentage": 90, "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, twinning', 'Excellent for copper and brass. Reveals grain boundaries and annealing twins clearly.', 'Grain boundaries dark, twins visible',
  ARRAY['copper', 'copper-alloy', 'brass', 'bronze'], ARRAY['steel', 'aluminum'],
  true, 'ammonium-persulfate', NULL,
  'Dissolve 10g (NH₄)₂S₂O₈ in 100ml distilled water. Prepare fresh solution.',
  'Immerse sample for 30-60 seconds. Swab gently. Rinse with water.',
  'Prepare fresh for best results. Solution decomposes over time.',
  'Store in dark bottle. Prepare fresh when needed. Shelf life: 1-2 days.',
  ARRAY['Ferric Chloride', 'Potassium Dichromate'], ARRAY['Ferric Chloride'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 9),

('Ferric Chloride', 'ferric-chloride', ARRAY['FeCl₃', 'Iron(III) Chloride'], ARRAY['copper', 'copper-alloy', 'bronze'], 'material-specific',
  '5-10g FeCl₃, 25ml HCl, 100ml H₂O', '5-10%',
  '[{"name": "Ferric Chloride", "amount": "5-10g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "25ml", "role": "solvent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 20, NULL, NULL, NULL,
  'Grain boundaries, phases', 'Good for copper alloys and bronzes. Reveals grain structure.', 'Grain boundaries dark',
  ARRAY['copper-alloy', 'bronze', 'brass'], ARRAY['steel', 'aluminum'],
  false, NULL, NULL,
  'Dissolve 5-10g FeCl₃ in 25ml HCl, then add 100ml water.',
  'Immerse sample for 20-40 seconds. Rinse with water.',
  'May stain sample if over-etched. Reduce time if needed.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Ammonium Persulfate'], ARRAY['Ammonium Persulfate'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 10),

-- Specialty Etchants
('Vilella''s Reagent', 'vilellas-reagent', ARRAY['Vilella''s Etchant'], ARRAY['tool-steel', 'high-speed-steel', 'carbides'], 'specialty',
  '1g Picric Acid, 5ml HCl, 100ml Ethanol', 'Mixed',
  '[{"name": "Picric Acid", "amount": "1g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "5ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 10, NULL, NULL, NULL,
  'Carbides, martensite, grain boundaries', 'Excellent for tool steels and high-speed steels. Reveals carbides clearly.', 'Carbides dark, matrix light',
  ARRAY['tool-steel', 'high-speed-steel', 'alloy-steel'], ARRAY['stainless-steel', 'aluminum'],
  true, 'vilellas', NULL,
  'Dissolve 1g picric acid in 5ml HCl, then add 100ml ethanol. CAUTION: Picric acid is explosive when dry.',
  'Immerse sample for 10-20 seconds. Rinse with ethanol then water.',
  'Keep picric acid wet. Never allow to dry. Use fresh solution.',
  'Store in dark bottle, keep wet. Extremely hazardous when dry.',
  ARRAY['4% Picral', 'Nital'], ARRAY['4% Picral'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 11),

('Murakami''s Reagent', 'murakamis-reagent', ARRAY['Murakami''s Etchant'], ARRAY['tungsten-carbide', 'hard-metals', 'carbides'], 'specialty',
  '10g K₃Fe(CN)₆, 10g KOH, 100ml H₂O', '10% each',
  '[{"name": "Potassium Ferricyanide", "amount": "10g", "role": "etching agent"}, {"name": "Potassium Hydroxide", "amount": "10g", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Carbides, phases in hard metals', 'Excellent for tungsten carbides and hard metals. Reveals carbide distribution.', 'Carbides colored, matrix light',
  ARRAY['tungsten-carbide', 'hard-metals', 'cemented-carbide'], ARRAY['steel', 'aluminum'],
  true, 'murakamis', NULL,
  'Dissolve 10g K₃Fe(CN)₆ and 10g KOH in 100ml water. Prepare fresh.',
  'Immerse sample for 30-60 seconds. May require heating to 50-60°C for some materials.',
  'Can be used hot for better results on hard materials.',
  'Store in dark bottle. Prepare fresh when needed.',
  ARRAY['Vilella''s Reagent'], ARRAY['Vilella''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 12),

-- Additional PACE Etchants
('8% Nital', '8-percent-nital', ARRAY['8% Nitric Acid', 'Nital 8%'], ARRAY['high-carbon-steel', 'tool-steel', 'very-hard-steel'], 'general-purpose',
  '8% Nitric Acid in Ethanol', '8%',
  '[{"name": "Nitric Acid", "percentage": 8, "role": "etching agent"}, {"name": "Ethanol", "percentage": 92, "role": "solvent"}]'::jsonb,
  'immersion', 20, NULL, NULL, NULL,
  'Grain boundaries, martensite, bainite, carbides', 'Very aggressive etchant for very hard steels. Use with caution.', 'Strong contrast between phases',
  ARRAY['high-carbon-steel', 'tool-steel', 'very-hard-steel'], ARRAY['stainless-steel', 'soft-materials'],
  true, 'nital-8', NULL,
  'Mix 8 ml concentrated nitric acid with 92 ml ethanol. Add acid slowly to ethanol.',
  'Immerse for 20-40 seconds. Very aggressive - use shorter times initially. Rinse thoroughly.',
  'Use for extremely hard steels. Monitor etching time very carefully.',
  'Store in dark glass bottle. Shelf life: 3-6 months.',
  ARRAY['5% Nital', '10% Nital', 'Vilella''s Reagent'], ARRAY['5% Nital', '10% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 13),

('10% Nital', '10-percent-nital', ARRAY['10% Nitric Acid', 'Nital 10%'], ARRAY['high-carbon-steel', 'tool-steel', 'extremely-hard-steel'], 'general-purpose',
  '10% Nitric Acid in Ethanol', '10%',
  '[{"name": "Nitric Acid", "percentage": 10, "role": "etching agent"}, {"name": "Ethanol", "percentage": 90, "role": "solvent"}]'::jsonb,
  'immersion', 25, NULL, NULL, NULL,
  'Grain boundaries, martensite, bainite, carbides', 'Most aggressive Nital concentration. For extremely hard materials that don''t respond to lower concentrations.', 'Strong contrast between phases',
  ARRAY['high-carbon-steel', 'tool-steel', 'extremely-hard-steel'], ARRAY['stainless-steel', 'soft-materials'],
  false, NULL, NULL,
  'Mix 10 ml concentrated nitric acid with 90 ml ethanol. Add acid slowly to ethanol.',
  'Immerse for 25-50 seconds. Most aggressive - use very short times initially and monitor closely. Rinse thoroughly.',
  'Use only for extremely hard steels that don''t respond to 8% Nital. Very aggressive - monitor etching time very carefully to avoid over-etching.',
  'Store in dark glass bottle. Shelf life: 3-6 months.',
  ARRAY['8% Nital', 'Vilella''s Reagent'], ARRAY['8% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 14),

('Adler''s Etchant', 'adlers-etchant', ARRAY['Adler''s Reagent'], ARRAY['stainless-steel', 'chromium-steel'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'Good for chromium steels and some stainless steels.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'chromium-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'adlers', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Similar to Kalling''s but with different proportions.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Kalling''s No. 2'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 14),

('Weck''s Etch', 'wecks-etch', ARRAY['Weck''s Reagent'], ARRAY['stainless-steel', 'duplex', 'color-etching'], 'material-specific',
  '100ml H₂O, 4g KMnO₄, 4g NaOH', '4% each',
  '[{"name": "Water", "amount": "100ml", "role": "solvent"}, {"name": "Potassium Permanganate", "amount": "4g", "role": "etching agent"}, {"name": "Sodium Hydroxide", "amount": "4g", "role": "etching agent"}]'::jsonb,
  'immersion', 60, 60, NULL, NULL,
  'Phases, grain boundaries', 'Color etchant for stainless steels. Produces colored phases.', 'Colored phases',
  ARRAY['stainless-steel', 'duplex-stainless-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'wecks', NULL,
  'Dissolve 4g KMnO₄ and 4g NaOH in 100ml water. Heat to 60°C.',
  'Immerse sample at 60°C for 60-120 seconds. Rinse with water.',
  'Use hot for best results. Produces color contrast.',
  'Store in glass bottle. Prepare fresh when needed.',
  ARRAY['Kalling''s No. 2'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 15),

('CU-PASS-SOL', 'cu-pass-sol', ARRAY['Copper Passivation Solution'], ARRAY['copper', 'copper-alloy', 'brass'], 'material-specific',
  'CuSO₄, NH₄OH, H₂O', 'Mixed',
  '[{"name": "Copper Sulfate", "role": "etching agent"}, {"name": "Ammonium Hydroxide", "role": "solvent"}, {"name": "Water", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, twinning', 'For copper and copper alloys. Reveals grain structure.', 'Grain boundaries dark',
  ARRAY['copper', 'copper-alloy', 'brass'], ARRAY['steel', 'aluminum'],
  true, 'cu-pass-sol', NULL,
  'Mix copper sulfate solution with ammonium hydroxide and water.',
  'Immerse sample for 30-60 seconds. Rinse with water.',
  'Good alternative to ammonium persulfate for copper.',
  'Store in glass bottle. Shelf life: several weeks.',
  ARRAY['Ammonium Persulfate'], ARRAY['Ammonium Persulfate'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 16),

('ASTM No. 30', 'astm-no-30', ARRAY['ASTM E407 No. 30'], ARRAY['stainless-steel', 'nickel-alloy'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'ASTM standard etchant for stainless steels and nickel alloys.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'nickel-alloy'], ARRAY['carbon-steel', 'aluminum'],
  true, 'astm-no-30', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Standard ASTM etchant formulation.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Kalling''s No. 2'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 17),

('Inconel Etchant', 'inconel-etchant', ARRAY['Inconel Reagent'], ARRAY['nickel-alloy', 'inconel', 'superalloy'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'Specifically for Inconel and nickel-based superalloys.', 'Grain boundaries dark',
  ARRAY['nickel-alloy', 'inconel', 'superalloy'], ARRAY['carbon-steel', 'aluminum'],
  true, 'inconel', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. May require swabbing. Rinse with water and ethanol.',
  'Works well on Inconel series alloys.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Glyceregia', 'Kalling''s No. 2'], ARRAY['Glyceregia'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 18),

('Carpenters', 'carpenters', ARRAY['Carpenter''s Reagent'], ARRAY['stainless-steel', 'chromium-steel'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'For chromium steels and stainless steels.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'chromium-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'carpenters', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Similar formulation to other copper chloride etchants.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Kalling''s No. 2', 'Adler''s Etchant'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 19),

('Dichromate Etchant', 'dichromate-etchant', ARRAY['Potassium Dichromate'], ARRAY['copper', 'copper-alloy', 'brass'], 'material-specific',
  '10g K₂Cr₂O₇, 5ml H₂SO₄, 100ml H₂O', '10%',
  '[{"name": "Potassium Dichromate", "amount": "10g", "role": "etching agent"}, {"name": "Sulfuric Acid", "amount": "5ml", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'For copper and copper alloys. Reveals grain structure.', 'Grain boundaries dark',
  ARRAY['copper', 'copper-alloy', 'brass'], ARRAY['steel', 'aluminum'],
  true, 'dichromate', NULL,
  'Dissolve 10g K₂Cr₂O₇ in 100ml water, then add 5ml H₂SO₄ slowly.',
  'Immerse sample for 30-60 seconds. Rinse with water.',
  'CAUTION: Contains dichromate and sulfuric acid. Use with proper PPE.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Ammonium Persulfate'], ARRAY['Ammonium Persulfate'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 20),

('Marble''s Reagent', 'marbles-reagent', ARRAY['Marble''s Etchant'], ARRAY['copper', 'copper-alloy', 'brass'], 'material-specific',
  '10g CuSO₄, 50ml NH₄OH, 50ml H₂O', 'Mixed',
  '[{"name": "Copper Sulfate", "amount": "10g", "role": "etching agent"}, {"name": "Ammonium Hydroxide", "amount": "50ml", "role": "solvent"}, {"name": "Water", "amount": "50ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, twinning', 'For copper and brass. Reveals grain boundaries and twins.', 'Grain boundaries dark, twins visible',
  ARRAY['copper', 'copper-alloy', 'brass'], ARRAY['steel', 'aluminum'],
  true, 'marbles', NULL,
  'Dissolve 10g CuSO₄ in 50ml water, then add 50ml NH₄OH.',
  'Immerse sample for 30-60 seconds. Rinse with water.',
  'Good for revealing annealing twins in copper.',
  'Store in glass bottle. Shelf life: several weeks.',
  ARRAY['Ammonium Persulfate', 'CU-PASS-SOL'], ARRAY['Ammonium Persulfate'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 21),

('Al-NaOH Etchant', 'al-naoh-etchant', ARRAY['Sodium Hydroxide', 'NaOH'], ARRAY['aluminum', 'aluminum-alloy'], 'material-specific',
  '10-20g NaOH, 100ml H₂O', '10-20%',
  '[{"name": "Sodium Hydroxide", "percentage": 10, "role": "etching agent"}, {"name": "Water", "percentage": 90, "role": "solvent"}]'::jsonb,
  'immersion', 30, 50, NULL, NULL,
  'Grain boundaries, precipitates', 'For aluminum alloys. Reveals grain structure.', 'Grain boundaries dark',
  ARRAY['aluminum', 'aluminum-alloy'], ARRAY['steel', 'titanium'],
  true, 'naoh', NULL,
  'CAUTION: NaOH is caustic. Dissolve 10-20g NaOH in 100ml water. Use at 50°C.',
  'Immerse sample at 50°C for 30-60 seconds. Rinse immediately with water.',
  'Use hot for better results. CAUTION: Caustic - use proper PPE.',
  'Store in plastic container. Label clearly. Caustic hazard.',
  ARRAY['Keller''s Reagent'], ARRAY['Keller''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 22),

('Klemm''s Reagent', 'klemm-s-reagent', ARRAY['Klemm''s Etchant'], ARRAY['stainless-steel', 'duplex', 'color-etching'], 'material-specific',
  '50g Na₂S₂O₅, 100ml H₂O', '50%',
  '[{"name": "Sodium Thiosulfate", "amount": "50g", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 60, NULL, NULL, NULL,
  'Phases, grain boundaries', 'Color etchant for stainless steels. Produces colored phases.', 'Colored phases',
  ARRAY['stainless-steel', 'duplex-stainless-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'klemms', NULL,
  'Dissolve 50g Na₂S₂O₅ in 100ml water.',
  'Immerse sample for 60-120 seconds. Rinse with water.',
  'Produces color contrast between phases.',
  'Store in glass bottle. Shelf life: several weeks.',
  ARRAY['Weck''s Etch'], ARRAY['Weck''s Etch'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 23),

('Winsteard''s Reagent', 'winsteards-reagent', ARRAY['Winsteard''s Etchant'], ARRAY['stainless-steel', 'chromium-steel'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'For chromium steels and stainless steels.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'chromium-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'winsteards', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Similar to other copper chloride based etchants.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Kalling''s No. 2'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 24),

('Waterless Kallings', 'waterless-kallings', ARRAY['Waterless Kalling''s'], ARRAY['stainless-steel', 'austenitic'], 'material-specific',
  '5g CuCl₂, 100ml HCl, 100ml Ethanol', 'Saturated',
  '[{"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "100ml", "role": "solvent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Austenite grain boundaries, sigma phase', 'Waterless version of Kalling''s reagent. Similar results to Kalling''s No. 2.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'austenitic-stainless-steel'], ARRAY['ferritic-steel', 'martensitic-steel'],
  true, 'waterless-kallings', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol. No water added.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Waterless formulation of Kalling''s reagent.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Kalling''s No. 2'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 25),

-- Additional PACE Etchants (from Shopify)
('ASTM No. 157', 'astm-no-157', ARRAY['ASTM E407 No. 157'], ARRAY['stainless-steel', 'nickel-alloy'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'ASTM standard etchant for stainless steels and nickel alloys.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'nickel-alloy'], ARRAY['carbon-steel', 'aluminum'],
  true, 'astm-no-157', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Standard ASTM etchant formulation.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['ASTM No. 30', 'Kalling''s No. 2'], ARRAY['ASTM No. 30'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 26),

('Beraha''s Reagent', 'berahas-reagent', ARRAY['Beraha''s Etchant'], ARRAY['stainless-steel', 'color-etching'], 'material-specific',
  '20g Na₂S₂O₅, 100ml H₂O, 1g K₂S₂O₅', 'Mixed',
  '[{"name": "Sodium Thiosulfate", "amount": "20g", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}, {"name": "Potassium Metabisulfite", "amount": "1g", "role": "etching agent"}]'::jsonb,
  'immersion', 60, NULL, NULL, NULL,
  'Phases, grain boundaries', 'Color etchant for stainless steels. Produces colored phases.', 'Colored phases',
  ARRAY['stainless-steel', 'duplex-stainless-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'berahas', NULL,
  'Dissolve 20g Na₂S₂O₅ and 1g K₂S₂O₅ in 100ml water.',
  'Immerse sample for 60-120 seconds. Rinse with water.',
  'Produces color contrast between phases.',
  'Store in glass bottle. Shelf life: several weeks.',
  ARRAY['Klemm''s Reagent', 'Weck''s Etch'], ARRAY['Klemm''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 27),

('Copper No. 1', 'copper-no-1', ARRAY['Copper Etchant No. 1'], ARRAY['copper', 'copper-alloy', 'brass'], 'material-specific',
  '10% (NH₄)₂S₂O₈ in H₂O', '10%',
  '[{"name": "Ammonium Persulfate", "percentage": 10, "role": "etching agent"}, {"name": "Water", "percentage": 90, "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, twinning', 'For copper and copper alloys. Reveals grain boundaries and annealing twins.', 'Grain boundaries dark, twins visible',
  ARRAY['copper', 'copper-alloy', 'brass'], ARRAY['steel', 'aluminum'],
  true, 'copper-no-1', NULL,
  'Dissolve 10g (NH₄)₂S₂O₈ in 100ml distilled water. Prepare fresh solution.',
  'Immerse sample for 30-60 seconds. Swab gently. Rinse with water.',
  'Prepare fresh for best results. Solution decomposes over time.',
  'Store in dark bottle. Prepare fresh when needed. Shelf life: 1-2 days.',
  ARRAY['Ammonium Persulfate', 'CU-PASS-SOL'], ARRAY['Ammonium Persulfate'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 28),

('Copper No. 2', 'copper-no-2', ARRAY['Copper Etchant No. 2'], ARRAY['copper', 'copper-alloy', 'bronze'], 'material-specific',
  '5-10g FeCl₃, 25ml HCl, 100ml H₂O', '5-10%',
  '[{"name": "Ferric Chloride", "amount": "5-10g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "25ml", "role": "solvent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 20, NULL, NULL, NULL,
  'Grain boundaries, phases', 'For copper alloys and bronzes. Reveals grain structure.', 'Grain boundaries dark',
  ARRAY['copper-alloy', 'bronze', 'brass'], ARRAY['steel', 'aluminum'],
  true, 'copper-no-2', NULL,
  'Dissolve 5-10g FeCl₃ in 25ml HCl, then add 100ml water.',
  'Immerse sample for 20-40 seconds. Rinse with water.',
  'May stain sample if over-etched. Reduce time if needed.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Ammonium Persulfate', 'Copper No. 1'], ARRAY['Ammonium Persulfate'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 29),

('Fry''s Reagent', 'frys-reagent', ARRAY['Fry''s Etchant'], ARRAY['stainless-steel', 'chromium-steel'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'For chromium steels and stainless steels.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'chromium-steel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'frys', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Similar formulation to other copper chloride etchants.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Kalling''s No. 2', 'Adler''s Etchant'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 30),

('Nickel Etchant', 'nickel-etchant', ARRAY['Nickel Reagent'], ARRAY['nickel', 'nickel-alloy', 'monel'], 'material-specific',
  '100ml HCl, 100ml Ethanol, 5g CuCl₂', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "100ml", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Copper Chloride", "amount": "5g", "role": "etching agent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases', 'For nickel and nickel alloys. Reveals grain structure.', 'Grain boundaries dark',
  ARRAY['nickel', 'nickel-alloy', 'monel'], ARRAY['carbon-steel', 'aluminum'],
  true, 'nickel', NULL,
  'Dissolve 5g CuCl₂ in 100ml HCl, then add 100ml ethanol.',
  'Immerse sample for 30-60 seconds. May require swabbing. Rinse with water and ethanol.',
  'Works well on nickel and nickel-based alloys.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['Inconel Etchant', 'Glyceregia'], ARRAY['Inconel Etchant'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 31),

('Oberhoffer''s Reagent', 'oberhoffers-reagent', ARRAY['Oberhoffer''s Etchant'], ARRAY['steel', 'iron', 'cast-iron'], 'material-specific',
  '50g CuCl₂, 150ml HCl, 150ml Ethanol, 50ml H₂O', 'Mixed',
  '[{"name": "Copper Chloride", "amount": "50g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "150ml", "role": "solvent"}, {"name": "Ethanol", "amount": "150ml", "role": "solvent"}, {"name": "Water", "amount": "50ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Phosphorus segregation, grain boundaries', 'Color etchant for revealing phosphorus segregation in steels and cast irons.', 'Colored phases',
  ARRAY['steel', 'iron', 'cast-iron'], ARRAY['stainless-steel', 'aluminum'],
  true, 'oberhoffers', NULL,
  'Dissolve 50g CuCl₂ in 150ml HCl, then add 150ml ethanol and 50ml water.',
  'Immerse sample for 30-60 seconds. Rinse with water and ethanol.',
  'Produces color contrast showing phosphorus segregation.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['2% Nital', '4% Picral'], ARRAY['2% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 32),

('Ti-AP-16', 'ti-ap-16', ARRAY['Titanium AP-16', 'Titanium Etchant AP-16'], ARRAY['titanium', 'titanium-alloy'], 'material-specific',
  '2ml HF, 5ml HNO₃, 100ml H₂O', '2%',
  '[{"name": "Hydrofluoric Acid", "amount": "2ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "5ml", "role": "oxidizer"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'swabbing', 5, NULL, NULL, NULL,
  'Alpha-beta phases, grain boundaries', 'Alternative etchant for titanium alloys. Reveals alpha and beta phases.', 'Alpha phase light, beta phase dark',
  ARRAY['titanium', 'titanium-alloy'], ARRAY['steel', 'aluminum'],
  true, 'ti-ap-16', NULL,
  'CAUTION: HF is extremely hazardous. Mix 2ml HF, 5ml HNO₃, and 100ml water in plastic container. Use fume hood and proper PPE.',
  'Swab sample for 5-15 seconds. Do not immerse. Rinse immediately with copious water.',
  'HF causes severe burns. Always use in fume hood with proper PPE. Have calcium gluconate gel available.',
  'Store in plastic container. Label clearly. Extremely hazardous - follow safety protocols.',
  ARRAY['Kroll''s Reagent'], ARRAY['Kroll''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 33),

-- Additional Common Etchants
('Aqua Regia', 'aqua-regia', ARRAY['Royal Water', 'Nitrohydrochloric Acid'], ARRAY['stainless-steel', 'nickel-alloy', 'platinum', 'gold'], 'material-specific',
  '75ml HCl, 25ml HNO₃', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "75ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "25ml", "role": "oxidizer"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, phases, carbides', 'Very aggressive etchant for noble metals and some stainless steels. Excellent for revealing grain structure in difficult-to-etch materials.', 'Grain boundaries dark, phases visible',
  ARRAY['stainless-steel', 'nickel-alloy', 'platinum', 'gold', 'palladium'], ARRAY['carbon-steel', 'aluminum', 'titanium'],
  false, NULL, NULL,
  'CAUTION: Extremely corrosive and produces toxic fumes. Mix 75ml concentrated HCl with 25ml concentrated HNO₃. Always add nitric acid to hydrochloric acid slowly. Prepare fresh - decomposes rapidly. Use in fume hood.',
  'Immerse sample for 30-60 seconds. Swab gently if needed. Rinse immediately with copious water, then ethanol. Very aggressive - monitor closely.',
  'Produces toxic chlorine and nitrosyl chloride fumes. Use only in fume hood with proper PPE. Prepare fresh for each use as it decomposes quickly. Very aggressive - may over-etch if left too long.',
  'Cannot be stored - prepare fresh for each use. Decomposes within hours. Store component acids separately.',
  ARRAY['Glyceregia', 'Kalling''s No. 2'], ARRAY['Glyceregia'],
  ARRAY['ASTM E407'], NULL,
  'published', true, 34),

('10% Oxalic Acid (Electrolytic)', '10-percent-oxalic-acid-electrolytic', ARRAY['Oxalic Acid Electrolytic', 'Electrolytic Oxalic'], ARRAY['stainless-steel', 'electrolytic', 'austenitic'], 'electrolytic',
  '10g (COOH)₂·2H₂O, 100ml H₂O', '10%',
  '[{"name": "Oxalic Acid Dihydrate", "amount": "10g", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'electrolytic', 30, NULL, 6, 0.1,
  'Grain boundaries, carbides, sigma phase', 'Electrolytic etchant for stainless steels. Reveals grain boundaries and secondary phases. Less aggressive than chemical etchants.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'austenitic-stainless-steel'], ARRAY['carbon-steel', 'aluminum'],
  false, NULL, NULL,
  'Dissolve 10g oxalic acid dihydrate in 100ml distilled water. Use as electrolyte in electrolytic etching setup.',
  'Use as electrolyte with stainless steel cathode. Apply 6V DC, 0.1 A/cm² current density for 30-60 seconds. Sample is anode. Rinse with water after etching.',
  'Ensure good electrical contact. If no etching occurs, check connections and increase voltage slightly. If over-etching, reduce time or current density.',
  'Store in glass bottle. Shelf life: several months. Solution is stable.',
  ARRAY['Kalling''s No. 2', 'Glyceregia'], ARRAY['Kalling''s No. 2'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 35),

('Chromic Acid (Electrolytic)', 'chromic-acid-electrolytic', ARRAY['Chromic Acid Electrolytic', 'Electrolytic Chromic'], ARRAY['stainless-steel', 'electrolytic', 'nickel-alloy'], 'electrolytic',
  '10g CrO₃, 100ml H₂O', '10%',
  '[{"name": "Chromic Trioxide", "amount": "10g", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'electrolytic', 60, NULL, 6, 0.1,
  'Grain boundaries, phases', 'Electrolytic etchant for stainless steels and nickel alloys. Good for revealing grain structure without over-etching.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'nickel-alloy', 'inconel'], ARRAY['carbon-steel', 'aluminum'],
  false, NULL, NULL,
  'CAUTION: Chromic acid is highly toxic and carcinogenic. Dissolve 10g CrO₃ in 100ml distilled water. Use in fume hood with proper PPE.',
  'Use as electrolyte with stainless steel cathode. Apply 6V DC, 0.1 A/cm² current density for 60-120 seconds. Sample is anode. Rinse thoroughly with water after etching.',
  'CAUTION: Chromic acid is a known carcinogen. Use only in fume hood with full PPE. Ensure good electrical contact. If no etching, check connections.',
  'Store in glass bottle with tight cap. Label clearly as toxic and carcinogenic. Shelf life: several months.',
  ARRAY['10% Oxalic Acid (Electrolytic)', 'Kalling''s No. 2'], ARRAY['10% Oxalic Acid (Electrolytic)'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 36),

('ASTM No. 1', 'astm-no-1', ARRAY['ASTM E407 No. 1'], ARRAY['general-purpose', 'carbon-steel'], 'general-purpose',
  '100ml Ethanol, 1-5ml HNO₃', '1-5%',
  '[{"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Nitric Acid", "amount": "1-5ml", "role": "etching agent"}]'::jsonb,
  'immersion', 10, NULL, NULL, NULL,
  'Grain boundaries, ferrite, pearlite', 'ASTM standard general-purpose etchant. Similar to Nital but with variable concentration. Good for carbon and low-alloy steels.', 'Pearlite darkens, ferrite remains light',
  ARRAY['carbon-steel', 'low-alloy-steel', 'cast-iron'], ARRAY['stainless-steel', 'aluminum'],
  false, NULL, NULL,
  'Mix 1-5ml concentrated nitric acid (HNO₃) with 100ml ethanol. Adjust concentration based on material hardness. Add acid to ethanol slowly with stirring.',
  'Immerse sample for 10-30 seconds. Adjust time based on concentration used. Rinse with ethanol then water. Dry with compressed air.',
  'Start with lower concentration (1-2%) for softer steels. Increase concentration for harder materials. If over-etched, reduce concentration or time.',
  'Store in dark glass bottle with tight cap. Keep away from light. Shelf life: 3-6 months if properly stored.',
  ARRAY['2% Nital', '3% Nital'], ARRAY['2% Nital', '3% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 37),

('ASTM No. 2', 'astm-no-2', ARRAY['ASTM E407 No. 2'], ARRAY['general-purpose', 'carbon-steel', 'cast-iron'], 'general-purpose',
  '4g Picric Acid, 100ml Ethanol', '4%',
  '[{"name": "Picric Acid", "amount": "4g", "role": "etching agent"}, {"name": "Ethanol", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 10, NULL, NULL, NULL,
  'Pearlite, cementite, grain boundaries', 'ASTM standard etchant for revealing pearlite structure. Does not attack ferrite grain boundaries as strongly as Nital.', 'Pearlite darkens, ferrite remains light',
  ARRAY['carbon-steel', 'cast-iron', 'pearlitic-steel'], ARRAY['stainless-steel', 'martensitic-steel'],
  false, NULL, NULL,
  'Mix 4g picric acid with 100ml ethanol. Warm slightly to dissolve. CAUTION: Picric acid is explosive when dry. Keep wet at all times.',
  'Immerse sample for 10-20 seconds. Swab if needed. Rinse with ethanol then water.',
  'Keep picric acid wet at all times. Never allow to dry. Store in water-wet condition. If over-etched, reduce time.',
  'Store in dark bottle, keep wet. Add water if solution dries. Extremely hazardous when dry. Never allow to dry completely.',
  ARRAY['4% Picral', '2% Nital'], ARRAY['4% Picral'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 38),

-- Additional Etchants for 95% Coverage
('10% Phosphoric Acid (Electrolytic)', '10-percent-phosphoric-acid-electrolytic', ARRAY['Phosphoric Acid Electrolytic', 'Electrolytic Phosphoric'], ARRAY['stainless-steel', 'electrolytic', 'austenitic'], 'electrolytic',
  '10ml H₃PO₄, 100ml H₂O', '10%',
  '[{"name": "Phosphoric Acid", "amount": "10ml", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'electrolytic', 30, NULL, 6, 0.1,
  'Grain boundaries, phases', 'Electrolytic etchant for stainless steels. Good for revealing grain structure without over-etching.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'austenitic-stainless-steel'], ARRAY['carbon-steel', 'aluminum'],
  false, NULL, NULL,
  'Mix 10ml concentrated phosphoric acid (H₃PO₄) with 100ml distilled water. Use as electrolyte in electrolytic etching setup.',
  'Use as electrolyte with stainless steel cathode. Apply 6V DC, 0.1 A/cm² current density for 30-60 seconds. Sample is anode. Rinse with water after etching.',
  'Ensure good electrical contact. If no etching occurs, check connections and increase voltage slightly. If over-etching, reduce time or current density.',
  'Store in glass bottle. Shelf life: several months. Solution is stable.',
  ARRAY['10% Oxalic Acid (Electrolytic)', 'Chromic Acid (Electrolytic)'], ARRAY['10% Oxalic Acid (Electrolytic)'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 39),

('Stead''s Reagent', 'steads-reagent', ARRAY['Stead''s Etchant'], ARRAY['cast-iron', 'graphite', 'iron'], 'material-specific',
  '10g CuCl₂, 40g MgCl₂, 20ml HCl, 1000ml H₂O', 'Mixed',
  '[{"name": "Copper Chloride", "amount": "10g", "role": "etching agent"}, {"name": "Magnesium Chloride", "amount": "40g", "role": "etching agent"}, {"name": "Hydrochloric Acid", "amount": "20ml", "role": "etching agent"}, {"name": "Water", "amount": "1000ml", "role": "solvent"}]'::jsonb,
  'immersion', 60, NULL, NULL, NULL,
  'Graphite, matrix structure', 'Specifically for revealing graphite in cast iron. Colors graphite and reveals matrix structure.', 'Graphite colored, matrix visible',
  ARRAY['cast-iron', 'gray-iron', 'ductile-iron'], ARRAY['steel', 'aluminum'],
  false, NULL, NULL,
  'Dissolve 10g CuCl₂ and 40g MgCl₂ in 1000ml water, then add 20ml HCl. Mix thoroughly.',
  'Immerse sample for 60-120 seconds. Swab gently if needed. Rinse with water.',
  'Excellent for revealing graphite distribution in cast irons. May require longer times for some materials.',
  'Store in glass bottle. Shelf life: several months.',
  ARRAY['2% Nital', '4% Picral'], ARRAY['2% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 40),

('Modified Kroll''s Reagent', 'modified-krolls-reagent', ARRAY['Modified Kroll''s', 'Kroll''s Modified'], ARRAY['titanium', 'titanium-alloy'], 'material-specific',
  '1ml HF, 3ml HNO₃, 100ml H₂O', '1%',
  '[{"name": "Hydrofluoric Acid", "amount": "1ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "3ml", "role": "oxidizer"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'swabbing', 5, NULL, NULL, NULL,
  'Alpha-beta phases, grain boundaries', 'Less aggressive version of Kroll''s reagent. Good for sensitive titanium microstructures.', 'Alpha phase light, beta phase dark',
  ARRAY['titanium', 'titanium-alloy'], ARRAY['steel', 'aluminum'],
  false, NULL, NULL,
  'CAUTION: HF is extremely hazardous. Mix 1ml HF, 3ml HNO₃, and 100ml water in plastic container. Use fume hood and proper PPE.',
  'Swab sample for 5-15 seconds. Do not immerse. Rinse immediately with copious water.',
  'HF causes severe burns. Always use in fume hood with proper PPE. Have calcium gluconate gel available. Less aggressive than standard Kroll''s.',
  'Store in plastic container. Label clearly. Extremely hazardous - follow safety protocols.',
  ARRAY['Kroll''s Reagent', 'Ti-AP-16'], ARRAY['Kroll''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 41),

('0.5% HF', '0-5-percent-hf', ARRAY['0.5% Hydrofluoric Acid', 'HF 0.5%'], ARRAY['aluminum', 'aluminum-alloy'], 'material-specific',
  '0.5ml HF, 99.5ml H₂O', '0.5%',
  '[{"name": "Hydrofluoric Acid", "amount": "0.5ml", "role": "etching agent"}, {"name": "Water", "amount": "99.5ml", "role": "solvent"}]'::jsonb,
  'immersion', 10, NULL, NULL, NULL,
  'Grain boundaries, precipitates', 'Light etchant for aluminum alloys. Less aggressive than Keller''s reagent. Good for sensitive microstructures.', 'Grain boundaries dark',
  ARRAY['aluminum', 'aluminum-alloy'], ARRAY['steel', 'titanium'],
  false, NULL, NULL,
  'CAUTION: HF is extremely hazardous. Mix 0.5ml HF with 99.5ml water in plastic container. Use fume hood and proper PPE.',
  'Immerse sample for 10-20 seconds. Swab if needed. Rinse immediately with copious water.',
  'HF causes severe burns. Use in fume hood with proper PPE. Have calcium gluconate gel available. Less aggressive than Keller''s reagent.',
  'Store in plastic container. Label clearly. Extremely hazardous.',
  ARRAY['Keller''s Reagent', 'Al-NaOH Etchant'], ARRAY['Keller''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 42),

('ASTM No. 3', 'astm-no-3', ARRAY['ASTM E407 No. 3'], ARRAY['general-purpose', 'carbon-steel', 'cast-iron'], 'general-purpose',
  '100ml Ethanol, 5ml HNO₃', '5%',
  '[{"name": "Ethanol", "amount": "100ml", "role": "solvent"}, {"name": "Nitric Acid", "amount": "5ml", "role": "etching agent"}]'::jsonb,
  'immersion', 15, NULL, NULL, NULL,
  'Grain boundaries, ferrite, pearlite', 'ASTM standard etchant. Similar to 5% Nital. Good for carbon and low-alloy steels.', 'Pearlite darkens, ferrite remains light',
  ARRAY['carbon-steel', 'low-alloy-steel', 'cast-iron'], ARRAY['stainless-steel', 'aluminum'],
  false, NULL, NULL,
  'Mix 5ml concentrated nitric acid (HNO₃) with 100ml ethanol. Add acid to ethanol slowly with stirring.',
  'Immerse sample for 15-30 seconds. Rinse with ethanol then water. Dry with compressed air.',
  'Similar to 5% Nital. If over-etched, reduce time. If under-etched, increase time slightly.',
  'Store in dark glass bottle with tight cap. Keep away from light. Shelf life: 3-6 months if properly stored.',
  ARRAY['5% Nital', '3% Nital'], ARRAY['5% Nital', '3% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 43),

('Sodium Metabisulfite (10%)', 'sodium-metabisulfite-10-percent', ARRAY['Na₂S₂O₅ 10%', 'Sodium Metabisulfite'], ARRAY['steel', 'prior-austenite', 'grain-boundaries'], 'specialty',
  '10g Na₂S₂O₅, 100ml H₂O', '10%',
  '[{"name": "Sodium Metabisulfite", "amount": "10g", "role": "etching agent"}, {"name": "Water", "amount": "100ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Prior austenite grain boundaries', 'For revealing prior austenite grain boundaries in quenched and tempered steels. Important for heat treatment analysis.', 'Prior austenite boundaries dark',
  ARRAY['quenched-steel', 'tempered-steel', 'alloy-steel'], ARRAY['stainless-steel', 'aluminum'],
  false, NULL, NULL,
  'Dissolve 10g sodium metabisulfite (Na₂S₂O₅) in 100ml distilled water. Prepare fresh solution.',
  'Immerse sample for 30-60 seconds. Swab gently if needed. Rinse with water.',
  'Prepare fresh for best results. Solution decomposes over time. Important for heat treatment analysis.',
  'Store in dark bottle. Prepare fresh when needed. Shelf life: 1-2 days.',
  ARRAY['2% Nital', '3% Nital'], ARRAY['2% Nital'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 44),

('10% Perchloric Acid (Electrolytic)', '10-percent-perchloric-acid-electrolytic', ARRAY['Perchloric Acid Electrolytic', 'Electrolytic Perchloric'], ARRAY['stainless-steel', 'electrolytic', 'nickel-alloy'], 'electrolytic',
  '10ml HClO₄, 90ml Acetic Acid', '10%',
  '[{"name": "Perchloric Acid", "amount": "10ml", "role": "etching agent"}, {"name": "Acetic Acid", "amount": "90ml", "role": "solvent"}]'::jsonb,
  'electrolytic', 20, NULL, 20, 0.5,
  'Grain boundaries, phases', 'Electrolytic etchant for stainless steels and nickel alloys. Very effective for revealing grain structure.', 'Grain boundaries dark',
  ARRAY['stainless-steel', 'nickel-alloy', 'inconel'], ARRAY['carbon-steel', 'aluminum'],
  false, NULL, NULL,
  'CAUTION: Perchloric acid is extremely dangerous and can explode. Mix 10ml perchloric acid (70%) with 90ml glacial acetic acid. Use only in specialized fume hood designed for perchloric acid. Never use with organic materials.',
  'Use as electrolyte with stainless steel cathode. Apply 20V DC, 0.5 A/cm² current density for 20-40 seconds at room temperature. Sample is anode. Rinse thoroughly with water after etching.',
  'CAUTION: Perchloric acid is extremely hazardous and can form explosive perchlorate salts. Use only in specialized perchloric acid fume hood. Never allow to dry. Clean all surfaces thoroughly after use. Very effective but requires extreme caution.',
  'Store in glass bottle in specialized perchloric acid storage area. Label clearly as extremely hazardous. Shelf life: prepare fresh when needed.',
  ARRAY['10% Oxalic Acid (Electrolytic)', 'Chromic Acid (Electrolytic)'], ARRAY['10% Oxalic Acid (Electrolytic)'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 45),

-- Additional Common Etchants from Guides
('Tucker''s Reagent', 'tuckers-reagent', ARRAY['Tucker''s Etchant'], ARRAY['aluminum', 'aluminum-alloy'], 'material-specific',
  '45ml HCl, 15ml HNO₃, 15ml HF, 25ml H₂O', 'Mixed',
  '[{"name": "Hydrochloric Acid", "amount": "45ml", "role": "etching agent"}, {"name": "Nitric Acid", "amount": "15ml", "role": "oxidizer"}, {"name": "Hydrofluoric Acid", "amount": "15ml", "role": "etching agent"}, {"name": "Water", "amount": "25ml", "role": "solvent"}]'::jsonb,
  'immersion', 30, NULL, NULL, NULL,
  'Grain boundaries, precipitates, phases', 'For revealing grain structure in aluminum alloys, especially heat-treated materials. Good for showing precipitates.', 'Grain boundaries dark',
  ARRAY['aluminum', 'aluminum-alloy', 'heat-treated-aluminum'], ARRAY['steel', 'titanium'],
  false, NULL, NULL,
  'CAUTION: HF is extremely hazardous. Mix 45ml HCl, 15ml HNO₃, 15ml HF, and 25ml water in plastic container. Use fume hood and proper PPE.',
  'Immerse sample for 15-45 seconds. Swab if needed. Rinse immediately with copious water.',
  'HF causes severe burns. Use in fume hood with proper PPE. Have calcium gluconate gel available. Good for heat-treated aluminum alloys.',
  'Store in plastic container. Label clearly. Extremely hazardous - follow safety protocols.',
  ARRAY['Keller''s Reagent', 'Al-NaOH Etchant'], ARRAY['Keller''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 46),

('Barker''s Reagent (Electrolytic)', 'barkers-reagent-electrolytic', ARRAY['Barker''s Etchant', 'Electrolytic Barker''s'], ARRAY['aluminum', 'aluminum-alloy', 'electrolytic'], 'electrolytic',
  'Fluoboric Acid (HBF₄)', 'Concentrated',
  '[{"name": "Fluoboric Acid", "role": "etching agent"}]'::jsonb,
  'electrolytic', 60, NULL, 20, 0.1,
  'Grain boundaries, interference colors', 'Electrolytic etchant for aluminum. Produces excellent grain boundary contrast and interference colors. Very effective for aluminum microstructures.', 'Grain boundaries dark, interference colors visible',
  ARRAY['aluminum', 'aluminum-alloy'], ARRAY['steel', 'titanium'],
  false, NULL, NULL,
  'CAUTION: Fluoboric acid is corrosive. Use concentrated fluoboric acid (HBF₄) as electrolyte. Use in fume hood with proper PPE.',
  'Use as electrolyte with aluminum or stainless steel cathode. Apply 15-30V DC, 0.1 A/cm² current density for 30-90 seconds. Sample is anode. Rinse thoroughly with water after etching.',
  'Produces excellent interference colors for phase identification. Ensure good electrical contact. If no etching, check connections and increase voltage slightly.',
  'Store in plastic container. Label clearly as corrosive. Shelf life: several months.',
  ARRAY['Keller''s Reagent', 'Tucker''s Reagent'], ARRAY['Keller''s Reagent'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 47),

('Ammonium Hydroxide + H₂O₂', 'ammonium-hydroxide-h2o2', ARRAY['NH₄OH + H₂O₂', 'Ammonia Peroxide'], ARRAY['copper', 'copper-alloy', 'brass'], 'material-specific',
  '50ml NH₄OH, 50ml H₂O₂ (3%)', '50:50',
  '[{"name": "Ammonium Hydroxide", "amount": "50ml", "role": "etching agent"}, {"name": "Hydrogen Peroxide", "amount": "50ml", "role": "oxidizer"}]'::jsonb,
  'immersion', 20, NULL, NULL, NULL,
  'Grain boundaries, twin boundaries', 'Standard etchant for copper and brass. Reveals grain boundaries and annealing twins. Fresh solution required for best results.', 'Grain boundaries dark, twins visible',
  ARRAY['copper', 'copper-alloy', 'brass'], ARRAY['steel', 'aluminum'],
  false, NULL, NULL,
  'Mix 50ml ammonium hydroxide (NH₄OH) with 50ml hydrogen peroxide (3% H₂O₂). Prepare fresh solution - decomposes quickly.',
  'Immerse sample for 10-30 seconds. Swab gently if needed. Rinse with water. Fresh solution works best.',
  'Solution decomposes quickly - prepare fresh for each use. If no etching occurs, prepare new solution. Very common and effective for copper.',
  'Cannot be stored - prepare fresh for each use. Decomposes within hours.',
  ARRAY['Ammonium Persulfate', 'ASTM No. 30'], ARRAY['Ammonium Persulfate', 'ASTM No. 30'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 48),

('ASTM No. 97', 'astm-no-97', ARRAY['ASTM E407 No. 97', 'ASTM 97'], ARRAY['nickel-alloy', 'electrolytic', 'fe-cr-ni'], 'electrolytic',
  '187.5g KOH, 245ml H₂O', '43%',
  '[{"name": "Potassium Hydroxide", "amount": "187.5g", "role": "etching agent"}, {"name": "Water", "amount": "245ml", "role": "solvent"}]'::jsonb,
  'electrolytic', 10, NULL, 2.5, 0.1,
  'Grain boundaries, phases', 'Electrolytic etchant for Fe-Cr-Ni alloys. Provides controlled etching for nickel alloys and stainless steels.', 'Grain boundaries dark',
  ARRAY['nickel-alloy', 'stainless-steel', 'fe-cr-ni-alloy'], ARRAY['carbon-steel', 'aluminum'],
  false, NULL, NULL,
  'CAUTION: KOH is caustic. Dissolve 187.5g potassium hydroxide (KOH) in 245ml distilled water. Use in fume hood with proper PPE.',
  'Use as electrolyte with stainless steel cathode. Apply 2.5V DC, 0.1 A/cm² current density for 5-15 seconds. Sample is anode. Rinse thoroughly with water after etching.',
  'CAUTION: Caustic - use proper PPE. Provides controlled etching. Ensure good electrical contact. If no etching, check connections.',
  'Store in plastic container. Label clearly as caustic. Shelf life: several months.',
  ARRAY['10% Oxalic Acid (Electrolytic)', 'Chromic Acid (Electrolytic)'], ARRAY['10% Oxalic Acid (Electrolytic)'],
  ARRAY['ASTM E407'], NULL,
  'published', false, 49);

-- Update slugs using the generate_etchant_slug function
UPDATE etchants SET slug = generate_etchant_slug(name) WHERE slug IS NULL;

