-- Seed ASTM standards data
INSERT INTO standards (standard, title, description, category, sort_order, tags, organization) VALUES
('ASTM E3', 'Standard Guide for Preparation of Metallographic Specimens', 'Comprehensive guide covering all aspects of metallographic specimen preparation including sectioning, mounting, grinding, polishing, and etching procedures.', 'Preparation', 1, ARRAY['preparation', 'specimen', 'grinding', 'polishing', 'mounting'], 'ASTM'),
('ASTM E407', 'Standard Practice for Microetching Metals and Alloys', 'Procedures for microetching metals and alloys to reveal microstructural features. Includes reagent preparation, application methods, and safety considerations.', 'Etching', 2, ARRAY['etching', 'microetching', 'reagents', 'safety'], 'ASTM'),
('ASTM E112', 'Standard Test Methods for Determining Average Grain Size', 'Methods for determining average grain size using comparison charts, planimetric (Jeffries) method, and intercept method. Includes procedures for different grain structures.', 'Analysis', 3, ARRAY['grain-size', 'analysis', 'measurement', 'planimetric', 'intercept'], 'ASTM'),
('ASTM E883', 'Standard Guide for Reflected-Light Photomicrography', 'Guidelines for capturing photomicrographs of metallographic specimens, including equipment setup, lighting, magnification selection, and image documentation.', 'Documentation', 4, ARRAY['photomicrography', 'documentation', 'imaging', 'microscopy'], 'ASTM'),
('ASTM E384', 'Standard Test Method for Microindentation Hardness of Materials', 'Test method for determining microindentation hardness using Knoop and Vickers indenters. Covers test procedures, equipment calibration, and reporting requirements.', 'Testing', 5, ARRAY['hardness', 'microindentation', 'knoop', 'vickers', 'testing'], 'ASTM'),
('ASTM E92', 'Standard Test Methods for Vickers Hardness and Knoop Hardness of Metallic Materials', 'Test methods for Vickers and Knoop hardness testing. Includes procedures, equipment requirements, and calculation methods.', 'Testing', 6, ARRAY['hardness', 'vickers', 'knoop', 'testing'], 'ASTM'),
('ASTM E18', 'Standard Test Methods for Rockwell Hardness of Metallic Materials', 'Test methods for Rockwell hardness testing using various scales (A, B, C, etc.). Covers procedures, equipment calibration, and test conditions.', 'Testing', 7, ARRAY['hardness', 'rockwell', 'testing'], 'ASTM'),
('ASTM E10', 'Standard Test Method for Brinell Hardness of Metallic Materials', 'Test method for Brinell hardness testing. Includes procedures, indenter specifications, test forces, and measurement requirements.', 'Testing', 8, ARRAY['hardness', 'brinell', 'testing'], 'ASTM'),
('ASTM E140', 'Standard Hardness Conversion Tables for Metals', 'Conversion tables for converting between different hardness scales (Rockwell, Brinell, Vickers, Knoop). Provides relationship tables for various materials.', 'Reference', 9, ARRAY['hardness', 'conversion', 'reference', 'tables'], 'ASTM'),
('ASTM E1245', 'Standard Practice for Determining the Inclusion or Second-Phase Constituent Content of Metals by Automatic Image Analysis', 'Practice for quantitative analysis of inclusions and second-phase constituents using automatic image analysis systems.', 'Analysis', 10, ARRAY['inclusions', 'image-analysis', 'quantitative', 'analysis'], 'ASTM'),
('ASTM E45', 'Standard Test Methods for Determining the Inclusion Content of Steel', 'Methods for determining the inclusion content of steel using comparison charts and image analysis. Covers rating procedures and reporting.', 'Analysis', 11, ARRAY['inclusions', 'steel', 'analysis', 'rating'], 'ASTM'),
('ASTM E562', 'Standard Test Method for Determining Volume Fraction by Systematic Manual Point Count', 'Manual point count method for determining volume fraction of phases or constituents in microstructures. Includes procedures and statistical considerations.', 'Analysis', 12, ARRAY['volume-fraction', 'point-count', 'quantitative', 'analysis'], 'ASTM'),
('ASTM E930', 'Standard Test Methods for Estimating the Largest Observed Grain Size (ALA Grain Size)', 'Methods for estimating the largest observed grain size in a microstructure, useful for quality control and failure analysis applications.', 'Analysis', 13, ARRAY['grain-size', 'ala', 'largest-grain', 'analysis'], 'ASTM'),
('ASTM E1181', 'Standard Test Methods for Characterizing Duplex Grain Sizes', 'Methods for characterizing materials with duplex (bimodal) grain size distributions. Includes procedures for measurement and reporting.', 'Analysis', 14, ARRAY['grain-size', 'duplex', 'bimodal', 'analysis'], 'ASTM'),
('ASTM E1951', 'Standard Guide for Calibrating Reticles and Light Microscope Magnifications', 'Guide for calibrating microscope magnifications and reticles to ensure accurate measurements. Includes procedures for various calibration methods.', 'Calibration', 15, ARRAY['calibration', 'microscope', 'magnification', 'reticles'], 'ASTM'),
('ASTM E2015', 'Standard Guide for Preparation of Plastics and Polymeric Specimens for Microstructural Examination', 'Guide for preparing polymeric materials for microstructural examination. Covers sectioning, mounting, polishing, and etching techniques for plastics.', 'Preparation', 16, ARRAY['preparation', 'plastics', 'polymers', 'specimen'], 'ASTM'),
('ASTM E340', 'Standard Practice for Macroetching Metals and Alloys', 'Practice for macroetching metals and alloys to reveal large-scale structural features. Includes reagent preparation and application methods.', 'Etching', 17, ARRAY['etching', 'macroetching', 'reagents'], 'ASTM'),
('ASTM E381', 'Standard Method of Macroetch Testing, Inspection, and Rating Steel Products, Comprising Bars, Billets, Blooms, and Forgings', 'Method for macroetch testing of steel products to reveal defects, segregation, and flow lines. Includes rating procedures and acceptance criteria.', 'Testing', 18, ARRAY['macroetching', 'steel', 'testing', 'inspection', 'rating'], 'ASTM'),
('ASTM E1578', 'Standard Guide for Laboratory Information Management Systems (LIMS)', 'Guide for implementing and using Laboratory Information Management Systems for tracking samples, procedures, and results.', 'Documentation', 19, ARRAY['lims', 'documentation', 'data-management'], 'ASTM'),
('ASTM E1919', 'Standard Guide for Worldwide Published Standards Relating to Metallography', 'Comprehensive guide listing published standards from various organizations worldwide related to metallography and materials testing.', 'Reference', 20, ARRAY['reference', 'standards', 'worldwide', 'metallography'], 'ASTM')
ON CONFLICT (slug) DO NOTHING;

-- Update slugs for standards that were auto-generated
UPDATE standards SET slug = generate_standard_slug(standard) WHERE slug IS NULL;

