-- Seed all equipment from pace-equipment.csv
-- This migration adds all equipment items with proper categorization and attributes

INSERT INTO equipment (item_id, name, slug, description, category, subcategory, is_pace_product, product_url, 
  blade_size_mm, blade_size_inches, automation_level, wheel_size_inches, max_cutting_capacity_mm, max_cutting_capacity_inches,
  suitable_for_sample_sizes, suitable_for_throughput, min_budget_level, tags, status)
VALUES
  -- ========== SECTIONING EQUIPMENT ==========
  
  -- MEGA Series Abrasive Cutters (already in 019, but including for completeness)
  ('MEGA-M250S', 'MEGA-M250S Manual Abrasive Cutter', 'mega-m250s', 
   'Manual wheel feed abrasive cutting machine for 10-inch (250 mm) abrasive blades.',
   'sectioning', 'manual-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/manual-abrasive-cutters.html',
   250, 10, 'manual', NULL, NULL, NULL,
   ARRAY['small'], ARRAY['low', 'medium'], 'budget-conscious',
   ARRAY['sectioning', 'abrasive', 'manual', '250mm', '10-inch'], 'active'),

  ('MEGA-T250S', 'MEGA-T250S Manual Abrasive Cutter', 'mega-t250s',
   'Manual wheel and table feed abrasive cutting machine for 10-inch (250 mm) abrasive blades.',
   'sectioning', 'manual-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/manual-abrasive-cutters.html',
   250, 10, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['low', 'medium'], 'budget-conscious',
   ARRAY['sectioning', 'abrasive', 'manual', '250mm', '10-inch', 'table-feed'], 'active'),

  ('MEGA-T300S', 'MEGA-T300S Manual Abrasive Cutter', 'mega-t300s',
   'Manual wheel and table feed abrasive cutting machine for 12-inch (300 mm) abrasive blades. Cutting capacity up to 4-inch (100 mm) solid stock.',
   'sectioning', 'manual-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/manual-abrasive-cutters.html',
   300, 12, 'manual', NULL, 100, 4,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'standard',
   ARRAY['sectioning', 'abrasive', 'manual', '300mm', '12-inch', 'table-feed'], 'active'),

  ('MEGA-T300A', 'MEGA-T300A Automated Abrasive Cutter', 'mega-t300a',
   'Automated / manual Y-axis with automated X-axis table feed and manual wheel feed abrasive cutting machine for 12-inch (300 mm) abrasive blades. Cutting capacity up to 4-inch (100 mm) solid stock.',
   'sectioning', 'automated-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/automated-abrasive-cutters.html',
   300, 12, 'automated', NULL, 100, 4,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['sectioning', 'abrasive', 'automated', '300mm', '12-inch', 'table-feed'], 'active'),

  ('MEGA-T350S', 'MEGA-T350S Manual Abrasive Cutter', 'mega-t350s',
   'Manual wheel and table feed abrasive cutting machine for 14-inch (350 mm) abrasive blades. Cutting capacity up to 4.5-inch (115 mm) solid stock.',
   'sectioning', 'manual-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/manual-abrasive-cutters.html',
   350, 14, 'manual', NULL, 115, 4.5,
   ARRAY['medium', 'large', 'very-large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['sectioning', 'abrasive', 'manual', '350mm', '14-inch', 'table-feed'], 'active'),

  ('MEGA-T350A', 'MEGA-T350A Automated Abrasive Cutter', 'mega-t350a',
   'Automated / manual Y-axis with automated X-axis table feed and manual wheel feed abrasive cutting machine for 14-inch (350 mm) abrasive blades. Cutting capacity up to 4.5-inch (115 mm) solid stock.',
   'sectioning', 'automated-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/automated-abrasive-cutters.html',
   350, 14, 'automated', NULL, 115, 4.5,
   ARRAY['medium', 'large', 'very-large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['sectioning', 'abrasive', 'automated', '350mm', '14-inch', 'table-feed'], 'active'),

  ('MEGA-T400S', 'MEGA-T400S Manual Abrasive Cutter', 'mega-t400s',
   'Manual wheel and table feed abrasive cutting machine for 16-inch (400 mm) abrasive blades.',
   'sectioning', 'manual-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/manual-abrasive-cutters.html',
   400, 16, 'manual', NULL, 115, 4.5,
   ARRAY['large', 'very-large'], ARRAY['medium', 'high'], 'premium',
   ARRAY['sectioning', 'abrasive', 'manual', '400mm', '16-inch', 'table-feed'], 'active'),

  ('MEGA-T400A', 'MEGA-T400A Automated Abrasive Cutter', 'mega-t400a',
   'Automated / manual Y-axis with automated X-axis table feed and manual wheel feed abrasive cutting machine for 16-inch (400 mm) abrasive blades.',
   'sectioning', 'automated-abrasive-sectioning', true,
   'https://metallographic.com/metallographic-equipment/abrasive-sectioning/automated-abrasive-cutters.html',
   400, 16, 'automated', NULL, 115, 4.5,
   ARRAY['large', 'very-large'], ARRAY['very-high'], 'enterprise',
   ARRAY['sectioning', 'abrasive', 'automated', '400mm', '16-inch', 'table-feed'], 'active'),

  -- PICO Series Precision Cutters
  ('PICO-155P', 'PICO-155P Precision Cutter', 'pico-155p',
   'Precision cutter with touch controls and built-in recirculating pump. Fits 3-inch (75 mm) up to 7-inch (175 mm) diameter blades. Variable speed 50-1500 rpm.',
   'sectioning', 'precision-wafering', true,
   'https://metallographic.com/metallographic-equipment/precision-wafering/gravity-feed-precision-cutters.html',
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small'], ARRAY['low', 'medium'], 'standard',
   ARRAY['sectioning', 'precision', 'wafering', 'diamond-blade'], 'active'),

  ('PICO-155S', 'PICO-155S Precision Cutter', 'pico-155s',
   'Precision cutter with touch-screen controls and built-in recirculating pump. Fits 3-inch (75 mm) up to 7-inch (175 mm) diameter blades. Variable speed 50-1500 rpm.',
   'sectioning', 'precision-wafering', true,
   'https://metallographic.com/metallographic-equipment/precision-wafering/gravity-feed-precision-cutters.html',
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small'], ARRAY['low', 'medium'], 'standard',
   ARRAY['sectioning', 'precision', 'wafering', 'diamond-blade'], 'active'),

  ('PICO-200A', 'PICO-200A Automated Precision Cutter', 'pico-200a',
   'Automated high speed table saw for precision cutting.',
   'sectioning', 'precision-wafering', true,
   'https://metallographic.com/metallographic-equipment/precision-wafering/table-feed-precision-cutters.html',
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['sectioning', 'precision', 'wafering', 'automated', 'diamond-blade'], 'active'),

  ('PICO-200S', 'PICO-200S Manual Precision Cutter', 'pico-200s',
   'High speed (500-3000 rpm) manual variable speed table saw for precision cutting.',
   'sectioning', 'precision-wafering', true,
   'https://metallographic.com/metallographic-equipment/precision-wafering/table-feed-precision-cutters.html',
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['sectioning', 'precision', 'wafering', 'manual', 'diamond-blade'], 'active'),

  -- PENTA Series Hand Grinders
  ('PENTA-5000A', 'PENTA-5000A 5-Station Hand Grinder', 'penta-5000a',
   '5-station hand grinder for coarse to fine grinding. Offers 5 stations with 240, 360, 600, 800 and 1200 grit abrasive.',
   'grinding', 'hand-grinding', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/hand-belt-grinders.html',
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['low', 'medium'], 'budget-conscious',
   ARRAY['grinding', 'hand-grinder', 'belt-grinder'], 'active'),

  ('PENTA-7500S', 'PENTA-7500S Belt Grinder', 'penta-7500s',
   'Wet or dry belt grinder for coarse grinding. Features a square grinding attachment to hold specimen mounts perpendicular during grinding.',
   'grinding', 'hand-grinding', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/hand-belt-grinders.html',
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'budget-conscious',
   ARRAY['grinding', 'belt-grinder', 'coarse-grinding'], 'active'),

  -- ========== MOUNTING EQUIPMENT ==========
  
  ('TP-7100S', 'TP-7100S TERAPRESS Pneumatic Mounting Press', 'tp-7100s',
   'Programmable pneumatic automated mounting press with easy force control. Features 1-inch to 2-inch interchangeable or fixed heater/molds, rapid ram movement, multiple cooling modes, and automatic programmable cycles.',
   'mounting', 'compression-mounting', true,
   'https://metallographic.com/metallographic-equipment/compression-mounting/pneumatic-mounting-press.html',
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['mounting', 'compression', 'pneumatic', 'automated'], 'active'),

  ('TP-7500S', 'TP-7500S TERAPRESS Hydraulic Mounting Press', 'tp-7500s',
   'Programmable electro-hydraulic automated compression mounting press with interchangeable molds. Features 1-inch to 2-inch interchangeable or fixed heater/molds, rapid ram movement, multiple cooling modes, and automatic programmable cycles.',
   'mounting', 'compression-mounting', true,
   'https://metallographic.com/metallographic-equipment/compression-mounting/hydraulic-mounting-press.html',
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large', 'very-large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['mounting', 'compression', 'hydraulic', 'automated'], 'active'),

  ('TeraVAC', 'TeraVAC Vacuum Impregnation System', 'teravac',
   'Vacuum impregnation system for room-temperature mounting. Removes air bubbles for clear mounts without heat application.',
   'mounting', 'castable-mounting', true,
   'https://metallographic.com/metallographic-equipment/castable-mounting/vacuum-mounting-system.html',
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['low', 'medium'], 'standard',
   ARRAY['mounting', 'castable', 'vacuum', 'cold-mounting'], 'active'),

  ('TeraVAC Pro', 'TeraVAC Pro Vacuum Impregnation System', 'teravac-pro',
   'Programmable castable vacuum impregnation chamber. Removes air bubbles for clear, bubble-free mounts essential for precision work and delicate samples.',
   'mounting', 'castable-mounting', true,
   'https://metallographic.com/metallographic-equipment/castable-mounting/vacuum-mounting-system.html',
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['medium', 'high'], 'premium',
   ARRAY['mounting', 'castable', 'vacuum', 'programmable', 'precision'], 'active'),

  ('TeraUV', 'TeraUV UV Curing Mounting System', 'terauv',
   'UV light mounting chamber for accelerated castable curing resins. Fastest mounting cycles for high-volume cold mounting applications.',
   'mounting', 'castable-mounting', true,
   'https://metallographic.com/metallographic-equipment/castable-mounting/uv-curing-system.html',
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['mounting', 'castable', 'uv-curing', 'fast-curing'], 'active'),

  -- ========== GRINDING & POLISHING EQUIPMENT ==========
  
  ('NANO-1000S', 'NANO-1000S Manual Grinder Polisher', 'nano-1000s',
   'Single wheel grinder polisher bench top polisher for 8 and/or 10-inch wheels. Features variable speed (100-1000 rpm), 1 hp motor, preset fast speed buttons, and auto mode.',
   'grinding', 'manual-grinding', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/nano.html',
   NULL, NULL, 'manual', ARRAY[8, 10], NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['low', 'medium'], 'standard',
   ARRAY['grinding', 'polishing', 'manual', 'single-wheel'], 'active'),

  ('NANO-1200S', 'NANO-1200S Manual Grinder Polisher', 'nano-1200s',
   'Single wheel grinder polisher bench top polisher for 12 and/or 14-inch wheels. Features variable speed (100-1000 rpm), 1.5 hp motor, preset fast speed buttons, and auto mode.',
   'grinding', 'manual-grinding', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/nano.html',
   NULL, NULL, 'manual', ARRAY[12, 14], NULL, NULL,
   ARRAY['medium', 'large', 'very-large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['grinding', 'polishing', 'manual', 'single-wheel', 'large-wheels'], 'active'),

  ('NANO-2000S', 'NANO-2000S Dual Wheel Grinder Polisher', 'nano-2000s',
   'Double wheel grinder polisher bench top polisher for 8 and/or 10-inch wheels. Features variable speed (100-1000 rpm), 1 hp motor, preset fast speed buttons, and auto mode.',
   'grinding', 'manual-grinding', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/nano.html',
   NULL, NULL, 'manual', ARRAY[8, 10], NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['medium', 'high'], 'standard',
   ARRAY['grinding', 'polishing', 'manual', 'dual-wheel'], 'active'),

  -- FEMTO Automatic Polishing Heads
  ('FEMTO-1100S', 'FEMTO-1100S Automatic Polishing Head', 'femto-1100s',
   'Automatic polishing head for use with NANO-1000S or NANO-2000S. Variable speed (0-200 rpm), pneumatically adjustable individual pistons for 1 to 6 specimens independent of each other.',
   'polishing', 'semi-automated-polishing', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/femto.html',
   NULL, NULL, 'semi-automated', ARRAY[8, 10], NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['medium', 'high'], 'premium',
   ARRAY['polishing', 'automated-head', 'individual-pistons'], 'active'),

  ('FEMTO-1500S', 'FEMTO-1500S Dual Mode Automatic Polishing Head', 'femto-1500s',
   'Dual individual and central automatic polishing head for use with NANO-1000S or NANO-2000S. Can polish 1-6 specimens independently or 3-6 using fixed central force for superior flatness.',
   'polishing', 'semi-automated-polishing', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/femto.html',
   NULL, NULL, 'semi-automated', ARRAY[8, 10], NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['polishing', 'automated-head', 'dual-mode', 'central-force'], 'active'),

  ('FEMTO-2200S', 'FEMTO-2200S Automatic Polishing Head', 'femto-2200s',
   'Automatic polishing head for use with NANO-1200S. Variable speed (0-200 rpm), pneumatically adjustable individual pistons for 1 to 6 specimens independent of each other.',
   'polishing', 'semi-automated-polishing', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/femto.html',
   NULL, NULL, 'semi-automated', ARRAY[12, 14], NULL, NULL,
   ARRAY['medium', 'large', 'very-large'], ARRAY['medium', 'high'], 'premium',
   ARRAY['polishing', 'automated-head', 'individual-pistons', 'large-wheels'], 'active'),

  ('FEMTO-2500S', 'FEMTO-2500S Dual Mode Automatic Polishing Head', 'femto-2500s',
   'Dual individual and central automatic polishing head for use with NANO-1200S. Can polish 1-6 specimens independently or 3-6 using fixed central force for superior flatness.',
   'polishing', 'semi-automated-polishing', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/femto.html',
   NULL, NULL, 'semi-automated', ARRAY[12, 14], NULL, NULL,
   ARRAY['medium', 'large', 'very-large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['polishing', 'automated-head', 'dual-mode', 'central-force', 'large-wheels'], 'active'),

  -- Specialized Polishing Equipment
  ('GIGA-S', 'GIGA-S Vibratory Polisher', 'giga-s',
   '9 or 12-inch metallurgical vibratory polisher. Designed to prepare even the most difficult to polish materials with a very gentle polishing action. Ideal for EBSD preparation.',
   'polishing', 'vibratory-polishing', true,
   'https://metallographic.com/metallographic-equipment/grinding-polishing/vibratory-polisher.html',
   NULL, NULL, 'automated', ARRAY[9, 12], NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium', 'high'], 'premium',
   ARRAY['polishing', 'vibratory', 'ebsd', 'gentle-polishing'], 'active'),

  ('ATTO-1000S', 'ATTO-1000S Controlled Micro-Precision Polisher', 'atto-1000s',
   'Controlled micro-precision polisher for plano-parallel sample preparation.',
   'polishing', 'precision-polishing', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small'], ARRAY['low', 'medium'], 'premium',
   ARRAY['polishing', 'precision', 'plano-parallel'], 'active'),

  ('ZETA-2000S', 'ZETA-2000S Automated Fluid Dispenser', 'zeta-2000s',
   '4-fluid automated / manual dispenser for controlling and regulating the application of abrasives such as diamond, alumina, colloidal silica and lubricant solutions onto the polishing surface.',
   'polishing', 'accessories', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['polishing', 'dispenser', 'automated', 'fluid-dispensing'], 'active'),

  -- ========== MICROSCOPY EQUIPMENT ==========
  
  ('IM-3000B', 'IM-3000B Inverted Metallurgical Microscope', 'im-3000b',
   'Inverted metallurgical microscope with Brightfield illumination. Includes 10X extra wide eyepiece, 4X, 10X, 20X, 50X and 100X infinite plan achromatic objectives, trinocular head, mechanical stage and color filters.',
   'microscopy', 'inverted-microscope', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'standard',
   ARRAY['microscopy', 'inverted', 'brightfield'], 'active'),

  ('IM-5000', 'IM-5000 Inverted Metallurgical Microscope', 'im-5000',
   'Inverted metallurgical microscope features bright-field, dark field, polarized light and differential interference contrast (DIC) illumination. Objectives include 5X, 10X, 20X, 50X and 100X.',
   'microscopy', 'inverted-microscope', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['medium', 'high'], 'premium',
   ARRAY['microscopy', 'inverted', 'dic', 'polarized-light'], 'active'),

  ('VM-100', 'VM-100 Digital Stereo Microscope', 'vm-100',
   'Digital stereo microscope with 0.7X ~ 4.5X electronic magnification with a zoom ratio of 6.5:1. Ideal for low magnification documentation of metallographic specimens prior to polishing and grinding.',
   'microscopy', 'stereo-microscope', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'standard',
   ARRAY['microscopy', 'stereo', 'digital', 'low-magnification'], 'active'),

  ('VM-500PLUS', 'VM-500PLUS Digital Stereo Microscope', 'vm-500plus',
   'Digital stereo microscope with autofocus and built-in measurement capabilities. 0.7X ~ 4.5X electronic magnification with a zoom ratio of 6.5:1.',
   'microscopy', 'stereo-microscope', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['medium', 'high'], 'premium',
   ARRAY['microscopy', 'stereo', 'digital', 'autofocus', 'measurement'], 'active'),

  ('ZMS0745T', 'ZMS0745T Trinocular Stereo Microscope', 'zms0745t',
   'Trinocular stereo microscope with magnification range of 7X to approximately 45X. Ideal for low magnification documentation of metallographic specimens prior to polishing and grinding.',
   'microscopy', 'stereo-microscope', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'standard',
   ARRAY['microscopy', 'stereo', 'trinocular'], 'active'),

  -- ========== HARDNESS TESTING EQUIPMENT ==========
  
  -- ALPHA Microhardness Testers
  ('ALPHA-MHT-1000VK', 'ALPHA-MHT-1000VK Dual Vickers/Knoop Microhardness Tester', 'alpha-mht-1000vk',
   'Dual Vickers/Knoop microhardness tester with auto turret instrument for Vickers and Knoop indenters independently. Variable testing forces (10, 25, 50, 100, 200, 300, 500, 1000 gram load), 10X, 20 and 40X objectives.',
   'hardness', 'microhardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['medium', 'high'], 'premium',
   ARRAY['hardness', 'microhardness', 'vickers', 'knoop', 'automated'], 'active'),

  ('ALPHA-MHT-1000Z', 'ALPHA-MHT-1000Z Micro Vickers Hardness Tester', 'alpha-mht-1000z',
   'Auto turret Micro Vickers hardness testing instrument for Vickers and Knoop indenters. Variable testing forces (10, 25, 50, 100, 200, 300, 500, 1000 gram load), 10X and 40X objectives.',
   'hardness', 'microhardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['medium', 'high'], 'premium',
   ARRAY['hardness', 'microhardness', 'vickers', 'knoop', 'automated'], 'active'),

  ('ALPHA-MHT-2000Z2', 'ALPHA-MHT-2000Z2 Precision Micro Vickers Hardness Tester', 'alpha-mht-2000z2',
   'Auto turret precision Micro Vickers hardness testing instrument for Vickers and Knoop indenters. Features include an auto turret head, large LCD screen.',
   'hardness', 'microhardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['high', 'very-high'], 'enterprise',
   ARRAY['hardness', 'microhardness', 'vickers', 'knoop', 'precision', 'automated'], 'active'),

  -- OMEGA Hardness Testers
  ('OMEGA-RT', 'OMEGA-RT Manual Rockwell Hardness Tester', 'omega-rt',
   'Manual basic low cost metallographic specimen Rockwell Hardness Tester. Load selection of 60, 100 and 150 Kgf (Rockwell).',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low'], 'budget-conscious',
   ARRAY['hardness', 'rockwell', 'manual'], 'active'),

  ('OMEGA-RT2', 'OMEGA-RT2 Manual Rockwell Hardness Tester', 'omega-rt2',
   'Manual basic low cost metallographic specimen Rockwell Hardness Tester. Load selection of 60, 100 and 150 Kgf (Rockwell).',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low'], 'budget-conscious',
   ARRAY['hardness', 'rockwell', 'manual'], 'active'),

  ('OMEGA-RT-60/150', 'OMEGA-RT-60/150 Semi-Automated Rockwell Hardness Tester', 'omega-rt-60-150',
   'Semi-automated digital Rockwell hardness tester. Features 60 Kgf, 100 Kgf and 150 Kgf loading, automatic conversion to 14 different hardness scales.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'semi-automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'standard',
   ARRAY['hardness', 'rockwell', 'semi-automated'], 'active'),

  ('OMEGA-DIGI-RT', 'OMEGA-DIGI-RT Semi-Automated Digital Rockwell Hardness Tester', 'omega-digi-rt',
   'Semi-automated digital Rockwell hardness tester. Color touch screen, motorized control of loading, dwell, and unloading. Rockwell - 60 Kgf, 100 Kgf and 150 Kgf loading.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'semi-automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['medium', 'high'], 'standard',
   ARRAY['hardness', 'rockwell', 'semi-automated', 'digital'], 'active'),

  ('OMEGA-AUTO-RT', 'OMEGA-AUTO-RT Automated Rockwell Hardness Tester', 'omega-auto-rt',
   'Automated digital Rockwell hardness tester. One touch operation, auto load change, auto lifting, auto loading, auto measuring, auto conversion, data transmission.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['hardness', 'rockwell', 'automated', 'fully-automated'], 'active'),

  ('OMEGA-ST', 'OMEGA-ST Manual Superficial Rockwell Hardness Tester', 'omega-st',
   'Manual basic low cost metallographic specimen Superficial Rockwell Hardness Tester. Load selection of 15, 30 and 45 Kgf (Superficial Rockwell).',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['low'], 'budget-conscious',
   ARRAY['hardness', 'superficial-rockwell', 'manual'], 'active'),

  ('OMEGA-DIGI-ST', 'OMEGA-DIGI-ST Semi-Automated Digital Superficial Rockwell Hardness Tester', 'omega-digi-st',
   'Semi-automated digital Superficial Rockwell hardness tester. Superficial Rockwell - 15 Kgf, 30 Kgr, and 45 Kgr loading.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'semi-automated', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['medium', 'high'], 'standard',
   ARRAY['hardness', 'superficial-rockwell', 'semi-automated', 'digital'], 'active'),

  ('OMEGA-AUTO-ST', 'OMEGA-AUTO-ST Automated Superficial Rockwell Hardness Tester', 'omega-auto-st',
   'Automated Superficial Rockwell hardness tester. One touch operation, auto load change, auto lifting, auto loading, auto measuring, auto conversion.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['hardness', 'superficial-rockwell', 'automated'], 'active'),

  ('OMEGA-DIGI-RST', 'OMEGA-DIGI-RST Semi-Automated Dual Rockwell/Superficial Rockwell Hardness Tester', 'omega-digi-rst',
   'Semi-automated digital dual Rockwell / Superficial Rockwell hardness tester. Rockwell/ Superficial Rockwell - 15 Kgf, 30 Kgr, 45 Kgr, 60 Kgf, 100 Kgf and 150 Kgf loading.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'semi-automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['medium', 'high'], 'standard',
   ARRAY['hardness', 'rockwell', 'superficial-rockwell', 'dual', 'semi-automated'], 'active'),

  ('OMEGA-AUTO-RST', 'OMEGA-AUTO-RST Automated Dual Rockwell/Superficial Rockwell Hardness Tester', 'omega-auto-rst',
   'Automated Dual Rockwell and Superficial Rockwell hardness tester. One touch operation, auto load change, auto lifting, auto loading, auto measuring, auto conversion.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['hardness', 'rockwell', 'superficial-rockwell', 'dual', 'automated'], 'active'),

  ('OMEGA-SRT-15/150', 'OMEGA-SRT-15/150 Automated Digital Rockwell/Superficial Rockwell Tester', 'omega-srt-15-150',
   'Automated digital Rockwell / Superficial Rockwell Testing machine. Load selection of 60, 100 and 150 kgf (Rockwell) and 15, 30 and 45 kgf (Superficial Rockwell).',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['hardness', 'rockwell', 'superficial-rockwell', 'dual', 'automated'], 'active'),

  ('OMEGA-HB', 'OMEGA-HB Manual Brinell Hardness Tester', 'omega-hb',
   'Basic economical manual Brinell tester designed to evaluate metallographic specimen hardness. Testing range of ~8 to 650 HBW. Test forces (kg) 62.5, 100, 125, 187.5, 250, 500, 750, 1000, 1500, 3000.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low'], 'budget-conscious',
   ARRAY['hardness', 'brinell', 'manual'], 'active'),

  ('OMEGA-HB-3000', 'OMEGA-HB-3000 Digital Brinell Hardness Tester', 'omega-hb-3000',
   'Digital Brinell tester for a testing range of ~8 to 650 HBW. Measurement is incorporated into unit with results displayed on a LCD screen.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'semi-automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium'], 'standard',
   ARRAY['hardness', 'brinell', 'digital'], 'active'),

  ('OMEGA-AUTO-HB', 'OMEGA-AUTO-HB Automated Brinell Hardness Tester', 'omega-auto-hb',
   'Fully automated Brinell tester designed to evaluate metallographic specimen hardness. Testing range of ~8 to 650 HBW. One key operation.',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['high', 'very-high'], 'premium',
   ARRAY['hardness', 'brinell', 'automated', 'fully-automated'], 'active'),

  ('OMEGA-5000-VZ', 'OMEGA-5000-VZ Semi-Automated Macro Vickers Hardness Tester', 'omega-5000-vz',
   'Semi-automated Macro Vickers hardness testing instrument with auto shifting between indenter and objective lens. Variable testing forces (1, 2, 2.5, 3, 5, 10, 20, 30 and 50 kilogram load).',
   'hardness', 'macrohardness', true,
   NULL,
   NULL, NULL, 'semi-automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['medium', 'high'], 'premium',
   ARRAY['hardness', 'vickers', 'macro', 'semi-automated'], 'active'),

  -- ========== CLEANING EQUIPMENT ==========
  
  ('UCLEAN', 'UCLEAN Ultrasonic Cleaner', 'uclean',
   'Ultrasonic cleaner for sample cleaning.',
   'cleaning', 'ultrasonic-cleaning', true,
   NULL,
   NULL, NULL, 'automated', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['cleaning', 'ultrasonic'], 'active'),

  -- ========== ACCESSORIES ==========
  
  ('RC-1000A', 'RC-1000A Recirculating Tank', 'rc-1000a',
   'Recirculating tank for NANO Polishers, includes tank, filter housing, pump, coarse, medium and fine filters.',
   'polishing', 'accessories', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['polishing', 'accessories', 'recirculating', 'filtration'], 'active'),

  ('TP-TANK', 'TP-TANK TERAPRESS Recirculation Tank', 'tp-tank',
   'TERAPRESS recirculation / cooling tank with pump.',
   'mounting', 'accessories', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['mounting', 'accessories', 'recirculating', 'cooling'], 'active'),

  ('MEGA-TANK', 'MEGA-TANK Recirculation Tank', 'mega-tank',
   'Recirculation / cooling tank with pump for MEGA series abrasive cutters.',
   'sectioning', 'accessories', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large', 'very-large'], ARRAY['low', 'medium', 'high', 'very-high'], 'standard',
   ARRAY['sectioning', 'accessories', 'recirculating', 'cooling', 'mega'], 'active'),

  ('SPEC-STORE', 'SPEC-STORE Storage Cabinet', 'spec-store',
   'Storage cabinet with 10 stainless steel drawers. Fits two 1-inch (25 mm), 1.25 (30 mm), 1.5-inch, 40 mm and 2-inch (50 mm) specimen storage trays per drawer.',
   'mounting', 'accessories', true,
   NULL,
   NULL, NULL, 'manual', NULL, NULL, NULL,
   ARRAY['small', 'medium', 'large'], ARRAY['low', 'medium', 'high'], 'standard',
   ARRAY['storage', 'accessories', 'specimen-storage'], 'active')

ON CONFLICT (item_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  automation_level = EXCLUDED.automation_level,
  blade_size_mm = EXCLUDED.blade_size_mm,
  blade_size_inches = EXCLUDED.blade_size_inches,
  wheel_size_inches = EXCLUDED.wheel_size_inches,
  updated_at = NOW();

-- Note: Software items (Materials Plus, Microhardness-Pro, Weld Check) are not included
-- as they are software products, not physical equipment for the lab setup recommendations

